### ISSUE TITLE
Combined searching of DIA umpire mgf files

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/containers#135]
_From @1Moe on February 9, 2017 4:4_

Hi there,

I have recently tried DIA-umpire to extract some pseudo MS/MS spectra from my DIA SWATH files (TripleTof 5600 wiff files) and I would like to use SearchGUI and Peptideshaker or ProteinPilot to search these mgf files. DIA umpire puts out 3 mgf files per 1 input file and the DIA umpire instructions say this:

> Each file corresponds to a different “quality level” of precursor ions (Q1= More than two isotopic peaks detected in MS1, Q2 = only two isotopic peak detected, Q3 = detected unfragmented precursor in MS2). These spectra are written to separate files, because they must be searched separately against a protein database as a consequence of differences in FDR estimates for these varying quality data.

I also found some info on the MatrixScience webpage suggesting using Q1 and Q3 together for best results http://www.matrixscience.com/blog/searching-dia-data-especially-swath.html

I'm now wondering if you could let me know the best strategy (in your opinion) to analyse the DIA umpire mgf files using searchgui and PS.

1) Do I have to search the 3 mgf files (coming from the same wiff file) separately and load together into peptideshake or can I search the 3 files together?

2) I have 50 biological samples with 3 technical replicates (3 injections per sample from the same tube). In theory I could generate 3x50x3 = 450 mgf files using DIA umpire. What would be the best combination to build a spectral library for DIA?

3) I tried searching the 3 mgf files together, comparing X!tandem and comet. Comet was the clear winner in terms of protein IDs - 9 IDs for Xtandem vs 127 IDs for Comet. Would you know the reason for this vast difference?

I have posted this here as well https://github.com/compomics/peptide-shaker/issues/243 to ask for the best strategy to search multiple mgf files.

Cheers
Moe

_Copied from original issue: BioContainers/specs#73_

**Comment by ypriverol** [comment]
_From @prvst on February 9, 2017 15:8_

Dear @1Moe ;

BioContainers and Peptide-Shaker are not the maintainers of DIA-Umpire. Here in our case, we are only providing DIA-Umpire as a container.

If you need assistance with DIA-Umpire, I suggest you take a look at the originall [website](http://diaumpire.sourceforge.net/), as described on the publication, they have a forum there where you can speak directly to the developers/maintainers.

regards

**Comment by ypriverol** [comment]
@1Moe As @prvst suggested, we are not in charge of the software providers. Are you using the DIA-UMPIRE BioContainer?  

Probably Chih-Chiang Tsou @cctsou you can respond to this question because you are the lead developer of DIA-UMPIRE. ?

@hbarsnes or @mvaudel do you have an idea? 

BTW I just moved this issue from the specs repo to here because is the proper place to discuss.

**Comment by cctsou** [comment]
Thank Yasset @ypriverol for bringing this thread to me. I would love to provide any help possible.

@1Moe : Do you intend to use DIA-Umpire for quantification analysis? One thing to keep in mind is DIA-Umpire's quantification module accepts only pep.xml format result. 

1. I think it's fine to search all the mgf files together. It makes everything easier.

2. Did you mean you want to build a library from DIA derived IDs? For building spectral library from DIA IDs, you can combine IDs from 3 mgf file for a single DIA file. But whether to combine IDs across runs and samples would depend on what you want to do in the end with the library and how diverse your samples or even the data acquisitions (different mass spec, fragmentation methods, chromatography, etc. ) are.

3. I guess there might be something wrong with the X!Tandem search, the difference can't be that huge. could you provide your X!Tandem and Comet search parameter files?

**Comment by 1Moe** [comment]
Thank you all for your help and quick reply!

Please see below for my response and also related to this, do you still recommend going from wiff to mzmL via the Sciex converter and then from mzML to mzXML via msconvert?

1) I'll search the 3 mgf files together 

2) yes, I'd like to build a DIA derived library for import into skyline - especially for retention time standards. As you said, I'm also not sure what is to be gained in terms of more IDs from running multiple samples together in 1 search.

3) see link https://drive.google.com/drive/folders/0BybCLLWRgDsUX2VTc0F1ZlpCMnM containing 
a) the parameters for X!tandem and Comet  for SearchGUI
b) the certificate of analysis and report from peptideshaker
c) the 3 mgf files from 1 wiff file (wiff - mzML - mzXML - mgf)

Regards
Moe

**Comment by cctsou** [comment]
The parameter files for Comet and X!Tandem look consistent, I don't see anything could cause the dramatic differences for ID numbers. Perhaps it's a good idea to check if you got huge difference in peptide IDs.

To convert wiff directly to mzXML, you can use msconvert, also you can use qtofpeakpicker which was found to be able to better remove noise peaks.

http://proteowizard.sourceforge.net/tools/qtofpeakpicker.html

**Comment by ypriverol** [comment]
@1Moe can we close this issue?

**Comment by 1Moe** [comment]
Yes, issue can be closed!
