### ISSUE TITLE
sra-tools do not work

### ISSUE THREAD

**Issue by antonkulaga** [BioContainers/containers#138]
Only sra-tools >=2.8.1 can access ncbi now. Please, update https://quay.io/repository/biocontainers/sra-tools and put the link to the docker file in readme (as it is not inside containers repo), I have issues with finding where the hell sra-tools are located inside the container

**Comment by ypriverol** [comment]
Hi @antonkulaga thanks for using biocontainers. This biocontainers is a mulled-based image. It means that it does not contain any dockerfile information (read: http://biocontainers.pro/docs/developer-manual/developer-intro/). However, you can find the information on the bioconda recipe here: http://biocontainers.pro/registry/#/showImages?domain=quay&repository=sra-tools&starred=false&modified=07%2F12%2F2016  

About creating the image for the new version 2.8.1. I will tag this issue as new container and we will try to create the image for you. If you would like to contribute to Biocontainers community, take a look about how to contribute http://biocontainers.pro/docs/developer-manual/developer-intro/ and give me your user, i can add you to our community.

**Comment by antonkulaga** [comment]
@ypriverol it would be nice if the recipe will generate a link to itself in the quay readme.

Regarding your proposal to collaborate. I am happy to join. I already made some containers for the tools I use in our pipelines, for instance https://github.com/antonkulaga/azimuth-docker

**Comment by ypriverol** [comment]
Hi @antonkulaga You can find the container here http://biocontainers.pro/registry/#/showImages?domain=quay&repository=sra-tools&starred=false&modified=28%2F02%2F2017 the image has been created. If you can test it would be great. Please, if that works to close the issue. 

I will open an issue in the registry to put the information of the latest version on the registry for  each container.

**Comment by bgruening** [comment]
3 different version are located here: https://quay.io/repository/biocontainers/sra-tools?tab=tags
@ypriverol can we remove the Dockerfile based ones?
