### ISSUE TITLE
Security issue in multi-user environment

### ISSUE THREAD

**Issue by tesujimath** [BioContainers/containers#147]
Firstly, I'm not quite sure if this is the right place to discuss this issue, which is a general problem about the risk of allowing unprivileged users to run BioContainers on a multi-user system.  I'll assume for now it's OK to discuss it here. :-)

We are investigating providing bioinformatics applications to our scientists by letting them use docker to run BioContainers, so all these users needing to run these containers will be in the docker group.  These users are scientists, not IT staff, so they are definitely not to be trusted with being root on the servers. Unfortunately, running a BioContainer (or a docker container in general) gives all these users the ability to write files all over the host filesystem, as root, by running a container as root and mounting the host filesystem like this (I'm using the qiime biocontainer just as an example)

```
host$ docker run -it -u 0 -v /:/host quay.io/biocontainers/qiime:1.9.1--py27_0 bash

bash-4.2# cd /host
bash-4.2# echo I trashed your system, muhaha > evil-user-was-here
bash-4.2# exit

host$ ls -l /
total 44
lrwxrwxrwx.   1 root     root     7 Apr  4 15:56 bin -> usr/bin
dr-xr-xr-x.   4 root     root  4096 Apr  4 16:34 boot
drwxr-xr-x   21 root     root  3360 Apr  5 09:11 dev
drwxr-xr-x. 107 root     root  8192 Apr  5 09:10 etc
-rw-r--r--    1 root     root    30 Apr  5 14:18 evil-user-was-here
drwxr-xr-x    3 root     root     0 Apr  5 09:15 home
lrwxrwxrwx.   1 root     root     7 Apr  4 15:56 lib -> usr/lib
lrwxrwxrwx.   1 root     root     9 Apr  4 15:56 lib64 -> usr/lib64
...

host$ cat /evil-user-was-here 
I trashed your system, muhaha
```

So I can't afford to put these users in the docker group.  It would seem I have to write a setgid C program to control access to the docker command, which will do the non-privileged user mapping and mounting of data directories from the host into the container.

It may be that using rkt instead of docker will simplify the whole approach.  But I don't think rkt is quite there with regard to running as unprivileged.

I can't be the only one to hit this issue on a multi-user system.  What are other people doing?

**Comment by osallou** [comment]
Hi.
This is indeed a docker issue, waiting for usernamespace support per
container. It is in roadmap but not planned and has kernel impacts.

To manage this in our facility, we developped godocker (
https://bitbucket.org/osallou/go-docker).
It manages the layer between user and docker , user executes jobs in
containers with user rights and it also mounts only allowed directories
(user home directory, some shared dirs in readonly, ...). Files on host are
written with real user id/gids.

Such things are the only secure ways to provide some docker containers in a
shared env.

Rkt does have the same issues (need the user namespace container feature)

Oliviet

**Comment by tesujimath** [comment]
Hi Oliviet,

Thanks for the info.  I am also looking at rkt.  I think what I need is much simpler than your godocker program.  I am thinking simply of a setuid wrapper which just invokes the underlying command with carefully managed user mapping and volume mounting.

cheers,
Simon

**Comment by osallou** [comment]
What we do is partly this uid mapping for execution. You should take care
of those possible different OS in containers to do this 'wrapper'.
And of course you must manage user authentication/authorization as user
will be faked in container.

**Comment by tesujimath** [comment]
I decided to write a wrapper for `rkt`, to enable use by unprivileged users.  `Rkt` seemed to be a better fit than `docker` for our use.  There's a first version available now.  Expect further refinements to come.  Here: [rktrunner](https://github.com/tesujimath/rktrunner)
