### ISSUE TITLE
How to integrate Debian based containers

### ISSUE THREAD

**Issue by osallou** [BioContainers/containers#148]
Hi,
as agreed, I have built Dockerfile for bioinformatics package from Debian archive like in bioshadock.
Before doing a pull request I have a few questions.
For the moment, it is available in my clone: https://github.com/osallou/containers/tree/master/debian

I have, for the moment, put eveything in a subdir debian, is it ok ? (to prevent a possible conflict with an existing package)

I have added a few LABEL with doi, copyright and available binaries in container when information is available.

My other questions are:

1.  how can we create the containers from those Dockerfile. There is a large quantity of new packages, and size will grow with new Debian packages. I could automate the build/tag/push to a Docker/Quay.io repository that would ease the process, but this cannot be done if I go through pull requests as build should be done only once PR is accepted. Doing this manually would be a huge amount of work.
2.  Same problem when a new release of a package is available. As Dockerfiles generation is automatic, triggering manually a build/tag in a repo would take a lot of time.
3. How does container appears in web site, is it an automatic pull from the repo?

**Comment by bgruening** [comment]
Hi @osallou,

thanks for starting this discussion. A debian subdir is fine, maybe even an own repo?

> 1.  how can we create the containers from those Dockerfile. There is a large quantity of new packages, and size will grow with new Debian packages. I could automate the build/tag/push to a Docker/Quay.io repository that would ease the process, but this cannot be done if I go through pull requests as build should be done only once PR is accepted. Doing this manually would be a huge amount of work.

Pushing is probably the only option given the awkward Dockerhub API at the moment. We can do this via Travis or and other CI even if you go through a PR. We are doing this in BioConda as well, just a matter of getting the build infrastructure right.

> 2.  Same problem when a new release of a package is available. As Dockerfiles generation is automatic, triggering manually a build/tag in a repo would take a lot of time.

Can you describe what you mean by automatic? We could even do the generation of Dockerfiles via travis if this is desirable.

As a general question, why can this not be entirely moved into the Debian infrastructure? So that debian is actually pushing to Dockerhub?

> 3. How does container appears in web site, is it an automatic pull from the repo?

Yes, automatically.

**Comment by osallou** [comment]
@bgruening ,
ok, so I could on regular basis update the debian related containers and create PRs, pushing at the same time on DockerHub the corresponding images tagged with corresponding version. Where should be push those containers? We need to create a specific repo (biocontainers-debian ?)

For a travis integration, my concern is building only new/updated containers. If travis is triggered on each commit in biocontainers  repo, then all containers will be rebuilt, no? Or, in bioconda, do you detect only modified Dockerfiles?

By automatic, I mean I habve a script that fetch Debian bioinformatics packages info and create corresponding Dockerfile if there is something new (new package or update).

For Debian infrastructure, there is no related plan in Debian, and here I focus only on DebianMed bioinformatics packages, removing lib and doc only packages.

**Comment by osallou** [comment]
One more question, regarding web site, how do you link container to its DockerHub url ?
For example, in debian/package_name/version/Dockerfile, how do you link to package biocontainers-debian/package_name:version container?

**Comment by bgruening** [comment]
> ok, so I could on regular basis update the debian related containers and create PRs, pushing at the same time on DockerHub the corresponding images tagged with corresponding version. Where should be push those containers? We need to create a specific repo (biocontainers-debian ?)

I might be alone with this opinion but I think `debian-med/` would be great. `biocontainers-debian-med` would also be ok. We could also think about a special tag system, like `biocontainers/samtools:1.3_debian`.

> For a travis integration, my concern is building only new/updated containers. If travis is triggered on each commit in biocontainers  repo, then all containers will be rebuilt, no? Or, in bioconda, do you detect only modified Dockerfiles?

BioConda has no Dockerfile, but we only build Conda packages for modified packages and those package, even if modified are only build if this exact version does not exists yet. So yes this is easily possible.

> By automatic, I mean I habve a script that fetch Debian bioinformatics packages info and create corresponding Dockerfile if there is something new (new package or update).

That's more or less what auto-mulled is doing without Dockerfiles. So in your case we need to handle this Dockerfile storage step somehow. So either someone needs to do it manually, or we do this also automatically and push them weekly to github - which makes the Dockerfiles someone redundant again imho.

> For Debian infrastructure, there is no related plan in Debian, and here I focus only on DebianMed bioinformatics packages, removing lib and doc only packages.

To bad! Would be great to have `debian-med` Docker channel that cares about this upstream.

**Comment by osallou** [comment]
Le jeu. 20 avr. 2017 à 17:17, Björn Grüning <notifications@github.com> a
écrit :

> ok, so I could on regular basis update the debian related containers and
> create PRs, pushing at the same time on DockerHub the corresponding images
> tagged with corresponding version. Where should be push those containers?
> We need to create a specific repo (biocontainers-debian ?)
>
> I might be alone with this opinion but I think debian-med/ would be
> great. biocontainers-debian-med would also be ok. We could also think
> about a special tag system, like biocontainers/samtools:1.3_debian.
>
let's keep separate registry repo for the moment.

> For a travis integration, my concern is building only new/updated
> containers. If travis is triggered on each commit in biocontainers repo,
> then all containers will be rebuilt, no? Or, in bioconda, do you detect
> only modified Dockerfiles?
>
> BioConda has no Dockerfile, but we only build Conda packages for modified
> packages and those package, even if modified are only build if this exact
> version does not exists yet. So yes this is easily possible.
>
> By automatic, I mean I habve a script that fetch Debian bioinformatics
> packages info and create corresponding Dockerfile if there is something new
> (new package or update).
>
> That's more or less what auto-mulled is doing without Dockerfiles. So in
> your case we need to handle this Dockerfile storage step somehow. So either
> someone needs to do it manually, or we do this also automatically and push
> them weekly to github - which makes the Dockerfiles someone redundant again
> imho.
>
well, biocontainers git repo is based on providing Dockerfiles (possibly
with attached data), so even I can automate build/push, we need to provide
a Dockerfile in tool/version directory. This also gives user the steps to
reproduce.

If I/someone commit directly, then automating updates is quite easy.

I could, at Genouest, run my script that
1) check for updates
2) generate dockerfiles from package info
3) build / tag /push container
4) commit to biocontainers repo new/updated tools in debian dir.

For Debian infrastructure, there is no related plan in Debian, and here I

**Comment by prvst** [comment]
hey guys;
@osallou why exactly do you need the Debian image and why it's not possible to use or integrate the Dockerfiles with our existing list and base image ?

**Comment by osallou** [comment]
Because i fetch debian packages and metadata to build dockerfile and detect
new or updated packages then install package in container , so needs a
debian image to install deb package.

Le jeu. 20 avr. 2017 17:43, Felipe Leprevost <notifications@github.com> a
écrit :

**Comment by ypriverol** [comment]
@osallou First of all official welcome to the project, I have been busy with many things and not really active in @BioContainers. A couple of ideas about integration with Debian packages: 

1. From the user/contributors perspective I will say that having only one namespace and central point make more sense than having multiple points. I would rather prefer to extend the recommendations saying we can have multiple base images like:

    I would prefer to have the central point for the based images here: 
        - The current image:  https://hub.docker.com/r/biocontainers/biocontainers/
     and three tags inside: 
       - latest: pointing the current based image latest version. 
       - debian-version: pointing to the current based image for Debian recommended/maintained by us. 
   We should keep @prvst track of the old based images for reproducibility purposes. 
 
2. About the actual containers:

In a previous discussion with @bgruening I mention the idea that we (as a community) have the namespace reserve for each software and handling with tags, the specific flavors, versions, images, etc. What that means in principal: 

let say we have software called OpenMS @timosachsenberg @BioContainers/contributors :

We should have across all biocontainers a unique namespace for OpenMS (it can be in Quay or DockerHub). Inside that OpenMS we should have the differnet versions of the containers with the specific tags such as: 

- 2.1.0--py35_boost1.63_0
-openms--2.1.0-debian

Whatever we define as the standard for creating the tags and names. I would prefer as a user to have an only namespace for the software and all possible containers in different versions, packages, based on different images, etc. I know some will argue that we don't need to curate/annotate software but we should only think about a well-defined namespace for the software and inside all the corresponding versions. In that case, we don't need biocontainers/samtools:1.3_debian we need biocontainers/samtools/
    -tag: 1.3_debian

Question: We should finally come with a standard for the tagging?

Another topic: some developers would like to have the possibility to push under quay.io in the namespace we define for them and know the other versions we are creating under their namespace. Then we need this definition soon.

**Comment by osallou** [comment]
@ypriverol , regarding base image, I use debian:stable-backports, I could "copy" it to biocontainers/biocontainers:debian-jessie-backports for tracability and use it as base image.

Regarding containers, we could build and tag/push to Docker biocontainers repo with biocontainers/packagename:X.Y.Z-debian name/tag.

Issue however is the Dockerfile. If a package have different origins (debian and other), the Dockerfile shown in DockerHub will be the one of the latest build. You won't see the Dockerfile for Debian and Dockerfile for the other origin.


Regarding git repo, I could either create a pull request, or commit directly in the repo. As this process is done automatically, committing directly would be easier for me, but what do you prefer?
Commiting directly would allow to create a commit per package change instead of a pull request containing all the packages modifications.

Regarding DockerHub repo, would your actual process detect changes in debian subdir and build/push/tag the container automatically to DockerHub ? Or should I push directly the containers to the hub ? (so will not be shown as automated builds)

**Comment by osallou** [comment]
@ypriverol , I have updated my cloned repo to use strech packages (https://github.com/osallou/containers/tree/master/debian, 828 containers).
What should be the way now ?

1) I can push a clone of debian-strech-backports to dockerhub/biocontainers/biocontainers:debian-strech-backports to track original image and update my Dockerfiles to use this image instead of official image (I need push rights in repo for this)
2) I can merge (once "FROM" is modified to use biocontainers:debian image)  my updates (debian sub directoy) though a pull request
3) How should we build/push the images ? I can build them locally and push them to a repo , but it would be best to have like for bioconda an automated process on git commit/merge to build the images and push/tag them to a biocontainers-debian repo
4) how will you integrate debian subdir in web site and make link to the related repo (how do you know where image is)?

Final remark on versions, tagging with "+" character is not allowed (as well as a few others I think). There are such characters in debian versions (but not only). So we need to trick those when tagging. But for matching, should be modify the version too in Dockerfile (replacing "+" by "-" for example)

**Comment by ypriverol** [comment]
> @ypriverol , I have updated my cloned repo to use strech packages (https://github.com/osallou/containers/tree/master/debian, 828 containers).
What should be the way now ?

@osallou  Now push into BioContainers!!!!. Before push are this containers complaint with the metadata, please review the labels etc? 

@osallou instead of having this containers in your own repo, why not having them into biocontainers containers repo. I can give you access to it and you can do the changes. The idea is that in the future people will complain/request/ etc using biocontainers github issues it would be good if they have all the containers in the same place. Do you think is possible? Also with this strategy we can organize better the software and have our major contributors of DockerFile in Biocontainers and the major contributors of DockerFile-free containers in BioConda. 

>I can push a clone of debian-strech-backports to dockerhub/biocontainers/biocontainers:debian-strech-backports to track original image and update my Dockerfiles to use this image instead of official image (I need push rights in repo for this)

Agree, we should extend our documentation to explain this change. Can you send me a short paragraph about this image, what packages contains, etc. I can update the documentation. 

>I can merge (once "FROM" is modified to use biocontainers:debian image) my updates (debian sub directoy) though a pull request. How should we build/push the images ? I can build them locally and push them to a repo , but it would be best to have like for bioconda an automated process on git commit/merge to build the images and push/tag them to a biocontainers-debian repo
how will you integrate debian subdir in web site and make link to the related repo (how do you know where image is)?
Here, I agree with you, the best way to move forward the Dockerfile-based containers is: 
  - Put all the containers Dockerfile in the same repository (as I said before and similar to BioConda).
  - Develop an automatic building system (like Bioconda) that can trigger and build all the 
     DockerFiles and push to our registry in DockerFile. We explore this in the past before using travis 
     and also DockerHub, didn't work because of resources limitations in both sites. The phenomenal 
     team (@pcm32) has their own system for that. I'm in conversations with the EBI Cloud Team for 
     that. Can you build that system in your side?  
>Final remark on versions, tagging with "+" character is not allowed (as well as a few others I think). There are such characters in debian versions (but not only). So we need to trick those when tagging. But for matching, should be modify the version too in Dockerfile (replacing "+" by "-" for example)

@prvst @bgruening @osallou we should have an agreement before anything on this topic to create and standard for the versioning. Can you create @osallou a separated issue for this and all of us agree?

**Comment by osallou** [comment]
I did not intend to keep in my own repo, but wanted to work on a fork to push my proposal and for discussions. Goal is to have them directly in biocontainers of course.
Regarding metadata etc... I think it is ok regarding your guidelines, you can see example here: https://github.com/osallou/containers/blob/master/debian/ampliconnoise/1.29-6/Dockerfile
The base image is the official debian stable (with backports) from DockerHub.

**Comment by johanneskoester** [comment]
You might want to consider [minideb](https://hub.docker.com/r/bitnami/minideb/). It is much smaller than the official base image and well maintained. We use it for the extended variant of the containers built from bioconda.

**Comment by osallou** [comment]
stretch-backports is only 45Mb and official, so looks quite small enough

**Comment by bgruening** [comment]
Just for the record, minideb is half the size of stretch-backports.

**Comment by osallou** [comment]
@ypriverol can you give me push access to biocontainers dockerhub repo to push the base image, renamed to biocontainers/biocontainers:debian-strech-backports

**Comment by ypriverol** [comment]
can you give the your dockerhub user

**Comment by osallou** [comment]
osallou  :-)

**Comment by ypriverol** [comment]
Done
