### ISSUE TITLE
FastQC 0.11.5

### ISSUE THREAD

**Issue by rspreafico** [BioContainers/containers#149]
1) the 0.11.15 Dockerfile-based container should probably be tagged 0.11.5

2) using the 0.11.5--1 Dockerfile-free container, fastqc cannot be invoked directly:

```
docker run --rm -it quay.io/biocontainers/fastqc:0.11.5--1 fastqc
standard_init_linux.go:178: exec user process caused "no such file or directory"
```

**Comment by bgruening** [comment]
Hi @rspreafico, sorry for my late answer. Can you please try this latest version `	0.11.5--pl5.22.0_2` from https://quay.io/repository/biocontainers/fastqc?tab=tags. FASTQC was not updated the last year and we enhanced our testing tremendously. This should not happen with containers that were created the last  5 month. If you find other containers, it's usually enough to retrigger a conda package rebuild add https://github.com/bioconda/bioconda-recipes.

Thanks for reporting!!!

**Comment by bgruening** [comment]
Multiple new versions available: https://quay.io/repository/biocontainers/fastqc?tab=tags
We should remove the Dockefile based on.
@ypriverol ok?

**Comment by ypriverol** [comment]
@rspreafico can we close this issue?

**Comment by rspreafico** [comment]
Yes thank you

**Comment by rspreafico** [comment]
Hi @bgruening I was just trying `0.11.5--pl5.22.0_2` as per thread above, but am getting this error:

```
Exception in thread "Thread-1" java.lang.Error: Probable fatal error:No fonts found.
```

According to [this link](http://wiki.hudson-ci.org/display/HUDSON/Hudson+got+java.awt.headless+problem), it seems that all it takes to fix it is to install fonts. Is that something that can be done to fix this container?

**Comment by jsalignon** [comment]
Hi all. I got the same issue than @rspreafico with containers fastqc:0.11.5--pl5.22.0_3 and 0.11.3--0

**Comment by bgruening** [comment]
@Bioninbo is the version 0.11.7--pl5.22.0_0 working for you?

**Comment by rioualen** [comment]
Hi, 
Any update on this issue? 

`Exception in thread "Thread-1" java.lang.Error: Probable fatal error:No fonts found.
`

I'm encountering it by using conda recipes for fastqc 0.11.5 and 0.11.7. I didn't have this problem before, using the same environment. Thanks for any input!

**Comment by osallou** [comment]
@bgruening i do not see any update on conda to see adding of fonts, there was no update on package?

**Comment by osallou** [comment]
Adding dep on dejavu-fonts should fix the issue

**Comment by bgruening** [comment]
Afaik the issue was the Java version not the fastqc version. If Java is used from conda-forge it should work and it was working last time I tested. @rioualen can you please post a small example to reproduce the error?

**Comment by rioualen** [comment]
I'm working on a Ubuntu 16.04 VM, using miniconda, and configured conda as recommended in the doc:

```
conda config --add channels r;
conda config --add channels defaults;
conda config --add channels conda-forge;
conda config --add channels bioconda
```

`conda create --name my_env python=3.6
`

`conda install make snakemake igv 
`

Then I'm running snakemake workflows where each rule uses its own environment, the fastqc one being originally:

```
dependencies:
  - fastqc
```

Used to work 3 months ago in Ubuntu 14.04 and conda environment using python 3.5.

Now under Ubuntu 16.04 and python 3.6 it raises the error, which I fixed like this for now: 

```
dependencies:
  - openjdk
  - fastqc=0.11.7
```

**Comment by bgruening** [comment]
Are you using conda to get fastqc or are you using containers?
(btw. the r-channel can be removed in conda)

**Comment by rioualen** [comment]
You mean i could go with just this and it'll work the same? 
```
conda config --add channels defaults;
conda config --add channels conda-forge;
conda config --add channels bioconda
```
If so it's pretty cool, didn't know that! 

Apart from that I don't use containers (yet?).

**Comment by bgruening** [comment]
ok, just to make sure, because your are asking in a container channel :)

**Comment by rioualen** [comment]
Oh right, sorry, I got lost in all the channels, should I move this elsewhere?

**Comment by bgruening** [comment]
Its fine I speak also Conda, so just keep asking ;)
