### ISSUE TITLE
Issue grabbing OpenMS image

### ISSUE THREAD

**Issue by bretttully** [BioContainers/containers#152]
I can grab `blast` with no issues:

```
$ docker pull biocontainers/blast
Using default tag: latest
latest: Pulling from biocontainers/blast
c62795f78da9: Pull complete 
d4fceeeb758e: Pull complete 
5c9125a401ae: Pull complete 
0062f774e994: Pull complete 
6b33fd031fac: Pull complete 
af6fedb9c521: Pull complete 
fd673780b023: Pull complete 
6126667f3f67: Pull complete 
bb944ca99002: Pull complete 
c40c4efd2448: Pull complete 
3ddbf72562fd: Pull complete 
8e7e9c932556: Pull complete 
46c6dd154e56: Pull complete 
d1bcaa2afb2e: Pull complete 
17063abba50e: Pull complete 
a90ebfcb0e1f: Pull complete 
bf4be4b2252c: Pull complete 
Digest: sha256:dfe163a03c5d3eca73a8fd3af5c3c16b8e7b9d36db187ba8b1f51c07d7f80794
Status: Downloaded newer image for biocontainers/blast:latest
```

but `openms` doesn't want to work:

```
$ docker pull biocontainers/openms
Using default tag: latest
Error response from daemon: manifest for biocontainers/openms:latest not found
```

Am I missing something?

**Comment by prvst** [comment]
HI @bretttully ;

We are having some difficulties to build large images like OpenMS since DockerHUb reduced their resources for automated builds. But we also have OpenMS deployed via Quay.io, please try the following:

docker pull quay.io/biocontainers/openms

Let me know if that works for you.
regards

**Comment by bretttully** [comment]
Sadly not
```
$ docker pull quay.io/biocontainers/openms
Using default tag: latest
Pulling repository quay.io/biocontainers/openms
Tag latest not found in repository quay.io/biocontainers/openms
```

**Comment by prvst** [comment]
hey @bgruening, any idea why is the Quay.io build not working ?

**Comment by osallou** [comment]
There is no latest tag but you call pull tag py35_boost1.63_0 on quay.io
Olivier

Le mar. 2 mai 2017 05:17, Felipe Leprevost <notifications@github.com> a
écrit :

**Comment by bgruening** [comment]
Hi, this is working for me:

```
docker run -it --rm quay.io/biocontainers/openms:2.1.0--py35_boost1.63_0 FileMerger --help
```

@bretttully can you confirm this?
Thanks!

**Comment by ypriverol** [comment]
@bgruening @prvst @osallou this is related to the long thread about the **latest** tag for every container in quay.io.

**Comment by bretttully** [comment]
Yep, that one is working. Thanks! 👍
