### ISSUE TITLE
skewer packaged on BioConda but not in BioContainers?

### ISSUE THREAD

**Issue by tesujimath** [BioContainers/containers#153]
We have some users needing skewer.  I see it is in BioConda, but no sign of it in BioContainers.

My understanding was that everything in BioConda gets pulled through to BioContainers.  I presume there may be a build problem blocking this.

Where can I get visibility of this?  We may be able to help with getting this working.

**Comment by bgruening** [comment]
@tesujimath the problem is that this recipe is really old and was never updated in the last 6 month. If you look at the recipe https://github.com/bioconda/bioconda-recipes/blob/master/recipes/skewer/meta.yaml it also does not fit our current standards in BioConda. So updating this recipe will give you a Container. Do you want to do this?

**Comment by tesujimath** [comment]
OK, I'll have a go at that (first BioContainer for me, hopefully a good starting point!)

**Comment by bgruening** [comment]
Cool thanks! I will assist you. Please ping me if you are ready :)

**Comment by tesujimath** [comment]
Great! I have something else pressing that I need to do tomorrow, then I'll get to this next.

**Comment by tesujimath** [comment]
@bgruening I fixed up the recipe for skewer, but have a few issues.  I pushed the recipe to my [github repo ](https://github.com/tesujimath/bioconda-recipes) on the skewer branch.

The first issue is when running `conda build`.  My recipe builds OK, and the test passes:
```
TEST END: skewer-0.2.2-1
```

But then it continues to build old version, and I get this, which I don't understand:
```
The following packages will be DOWNGRADED due to dependency conflicts:

    skewer: 0.2.2-1 local --> 0.1.126-0 local
```

When I ran `./simulate-travis.py --package skewer` it seemed OK.  I didn't get a lint warning about my new recipe, although it did check all the others, which I didn't expect, as I thought I asked it just to look at skewer.

I pushed it anyway, and [Travis-CI complained](https://travis-ci.org/tesujimath/bioconda-recipes/jobs/228602492).  The Travis error seems a bit strange to me:
```
bioconda-utils lint: error: argument --git-range: expected at least one argument
```

Any suggestions about either or both of these issues?

PS. I'm testing on Linux, so don't really expect any success with the OSX job on Travis-CI yet.

**Comment by bgruening** [comment]
If you have both version in the same folder it will build both skewer version, this is a normal behavior. The last error is strange. I will look at it, but it will go away if you create a PR ... you can label it as WIP and I can look at it.

Thanks!

**Comment by bgruening** [comment]
Thanks to @tesujimath PR on BioConda a new container is here: https://quay.io/repository/biocontainers/skewer?tab=tags

**Comment by tesujimath** [comment]
@bgruening Is there some propagation delay in being able to use this?  I'm getting a 403 error from rkt when trying to use this container:
```
# rkt --insecure-options=image run quay.io/biocontainers/skewer:0.2.2--1 --exec skewer
run: bad HTTP status code: 403
```

**Comment by bgruening** [comment]
A small, around 10 mins. Docker works for me, can you please try again?

**Comment by tesujimath** [comment]
Ah, I see docker works, but not rkt.  I wonder why that is.  I'll investigate further.

**Comment by tesujimath** [comment]
Sorry, I see it just started working with rkt too.  Sorry for the noise.

**Comment by bgruening** [comment]
Cool! Enjoy!

**Comment by bgruening** [comment]
We are rebuilding all packages in the next week so these failures should be less and less.
