### ISSUE TITLE
Contribution of PhenoMeNal release containers to biocontainers docker hub namespace

### ISSUE THREAD

**Issue by pcm32** [BioContainers/containers#155]
Hi there!

We are about to start a new release cycle for our containers at PhenoMeNal Project (this means, making releases for our containers out of the dev versions). These are mostly metabolomics containers:

https://phenomenal-h2020.eu/jenkins/view/%20A.-%20Container%20tools/

This presents the opportunity for us to setup our Jenkins to push automatically all release tagged images of our containers to biocontainers in addition to our own public registry. So all dev_ tagged containers don't get pushed, but only the release versions. A few current caveats:

- Unfortunately we don’t follow all of biocontainers guidelines (we do align in the versions and software.versions labels and few others, but not a lot more).
- We don’t use the biodocker/biocontainer user inside the container. This is mostly due to functionality concerning file ownership on share file system writes. We have now a solution for this on Kubernetes/Galaxy, but this hasn't yet permeated to our tools. But will come.

Question: do you want `:latest` to be pushed as well?

This would be a direct `docker push biocontainers/tool-name:phenomenal-<our-version-tag>` to the biocontainers dockerhub account done from our CI right after building the image. We are happy to add phenomenal to prefix the tag to use the biocontainers namespace instead of ours, as suggested in the docker push line example.

Other **big caveat is**: we are due to start this release cycle **at the most tomorrow**, so if these conditions are deemed unacceptable, we would need to leave this functionality for our next release cycle in 6 more months (and only do the pushes then, in more favourable conditions for biocontainers), as we cannot delay this release. My proposition is to start as explained and improve later on, but up to you of course. I would completely understand if you feel that this is too much disorder and would mess up things.

I apologise for coming so much on top of dates, but past months have been very busy towards this release and other engagements. Let me know your thoughts!

**Comment by ypriverol** [comment]
As we discuss, I will vote yes for this deploy as soon as possible and start using DockerHub for all these initiatives. We need only a compromise from you guys about: 

- Improve in the short term the metadata of all the containers to be Biocontainers compliant. 

You can update the latest version if you decided. I will give you admin permission when @prvst and @bgruening  give their opinion. Please vote as soon as possible.

**Comment by prvst** [comment]
Hey @pcm32 , @ypriverol 

:+1: I approve this message!  

Edit: Let us know if you need assistance with anything

**Comment by bgruening** [comment]
:+1: for me as long as it stays in dockerhub and we try to improve the metadata situation :)
Thanks @pcm32!
