### ISSUE TITLE
Manage tagging of software versions

### ISSUE THREAD

**Issue by osallou** [BioContainers/containers#156]
tagging an image with "+" character is not allowed (as well as a few others I think)

There are such characters in debian versions (but not only).

So we need to trick those when tagging (could replace for example *+* by *-* (to be discussed on special char and rules for modification).

However, to match a container image vs its Dockerfile, we maybe also modify the version in Dockerfile

**Comment by ypriverol** [comment]
- @osallou can you put an example. 
- @bgruening do we have any standard in BioConda for the versions.

**Comment by bgruening** [comment]
@ypriverol yes the conda naming schema of packages.

**Comment by ypriverol** [comment]
Can you point me to the documentation.

**Comment by bgruening** [comment]
https://conda.io/docs/building/pkg-name-conv.html

**Comment by osallou** [comment]
Examples quite frequent found in debian: aegean/0.15.2+dfsg-1, aevol/4.4-1+b4, biosquid-dev/1.9g+cvs20050121-7
Behind the "-", this is debian related, before it is upstream related

**Comment by osallou** [comment]
@bgruening this link does not specify contraining rules regarding version naming.
"+" and others are forbidden on DockerHub
Link only specifies: "A version number or string, often similar to X.Y or X.Y.Z, but may take other forms as well"

We need to map versions like "1.9g+cvs20050121-7" to a Docker enabled version.

**Comment by osallou** [comment]
base image uploaded, now remains version tagging issue and I can push my Dockerfiles and build images before pushing them to dockerhub like biocontainers/softwarename:debian-XXX
