### ISSUE TITLE
ITSx

### ISSUE THREAD

**Issue by Andreas-Bio** [BioContainers/containers#159]
request:
http://microbiology.se/software/itsx/

**Comment by ecirtap** [comment]
Hi, as itsx is in Bioconda, a biocontainer has already been automatically generated for it, but in this (uncommon) case, it was private. Fixed by the BioContainers team. 

You can try it : docker pull quay.io/biocontainers/itsx

**Comment by bgruening** [comment]
Thanks @ecirtap for finding this!
