### ISSUE TITLE
phylobayes

### ISSUE THREAD

**Issue by Andreas-Bio** [BioContainers/containers#162]
request:
http://megasun.bch.umontreal.ca/People/lartillot/www/downloadmpi.html

**Comment by ecirtap** [comment]
Hi, I have began to write a recipe for this software, but I need some help to test the compiled binary (I have no skill at all in this domain). Could you join here a smoke test for this software ?  I mean by this a command line and a minimal dataset to test in a few seconds that the software is working. Thanks in advance!

**Comment by Andreas-Bio** [comment]
So what is the final decision?
