### ISSUE TITLE
vcftools vcf-merge error: tabix not found

### ISSUE THREAD

**Issue by buchanae** [BioContainers/containers#172]
docker run -v `pwd`:/data biocontainers/vcftools:latest vcf-merge data/muse.normalized.vcf data/somaticsniper.normalized.vcf data/varscan.snp.normalized.vcf data/radia.normalized.vcf
Unable to find image 'biocontainers/vcftools:latest' locally
latest: Pulling from biocontainers/vcftools
c62795f78da9: Already exists
d4fceeeb758e: Already exists
5c9125a401ae: Already exists
0062f774e994: Already exists
6b33fd031fac: Already exists
7a5724671bcc: Already exists
aa65e16b8de6: Already exists
baa42fddbf04: Already exists
51705efff363: Already exists
46c05ebab1c2: Already exists
0b016b186f2b: Already exists
5b3a6e3318e6: Already exists
da00ecd26c95: Already exists
ec716ccd774c: Already exists
9572d4ef95b4: Already exists
fb7f38888cd9: Already exists
4bb2d3630bbb: Pull complete
Digest: sha256:c9f2300ee4d9c53cf738987d1dc791f22a5683401df52f5467141e4f57413964
Status: Downloaded newer image for biocontainers/vcftools:latest
sh: 1: tabix: not found
The command "tabix" not found, please add it to your PATH

 at /usr/local/share/perl/5.22.1/Vcf.pm line 172.
	Vcf::throw(Vcf4_2=HASH(0x1242e00), "The command \"tabix\" not found, please add it to your PATH\x{a}") called at /usr/local/share/perl/5.22.1/Vcf.pm line 2672
	VcfReader::get_chromosomes(Vcf4_2=HASH(0x1242e00)) called at /usr/local/bin/vcf-merge line 197
	main::init_cols(HASH(0x16e37e0), Vcf4_2=HASH(0x16447a0)) called at /usr/local/bin/vcf-merge line 279
	main::merge_vcf_files(HASH(0x16e37e0)) called at /usr/local/bin/vcf-merge line 12

**Comment by osallou** [comment]
tabix package is missing in container

**Comment by osallou** [comment]
could you just test install tabix package and container and checking it is ok before with fix the container?
copy your input files in /tmp (to avoid files creation as root in your current directory) and:

    docker run -it --rm --user root -v /tmp:/data biocontainers/vcftools:latest /bin/bash
    # apt-get install tabix
    # vcf-merge .....

thanks
