### ISSUE TITLE
Entrez-direct container is broken

### ISSUE THREAD

**Issue by sminot** [BioContainers/containers#178]
I tested all three versions of the `entrez-direct` image (listed here: https://quay.io/repository/biocontainers/entrez-direct?tab=tags), and each of them failed to complete the Entrez-direct testing script listed by NCBI (https://dataguide.nlm.nih.gov/edirect/install.html)

My output (using the newest image, `quay.io/biocontainers/entrez-direct:7.00--pl5.22.0_1`) was:

```
***********************
esearch version:
7.00
xtract version:
7.10
EDirect install status:
***********************
```

While the desired output was:

```
***********************
esearch version:
7.00
xtract version:
7.00
EDirect install status:
OK
***********************
```

The error message that I saw was:

```
501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)
No do_post output returned from 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=Babalobi%20OO%5Bau%5D%20AND%202008%5Bpdat%5D&retmax=0&usehistory=y&edirect=7.00&tool=edirect&email=root+@b18f725d2236'
Result of do_post http request is
$VAR1 = bless( {
                 '_request' => bless( {
                                        '_headers' => bless( {
                                                               'user-agent' => 'libwww-perl/6.26',
                                                               'content-type' => 'application/x-www-form-urlencoded'
                                                             }, 'HTTP::Headers' ),
                                        '_method' => 'POST',
                                        '_uri' => bless( do{\(my $o = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi')}, 'URI::https' ),
                                        '_content' => 'db=pubmed&term=Babalobi%20OO%5Bau%5D%20AND%202008%5Bpdat%5D&retmax=0&usehistory=y&edirect=7.00&tool=edirect&email=root+@b18f725d2236'
                                      }, 'HTTP::Request' ),
                 '_headers' => bless( {
                                        'content-type' => 'text/plain',
                                        '::std_case' => {
                                                          'client-date' => 'Client-Date',
                                                          'client-warning' => 'Client-Warning'
                                                        },
                                        'client-warning' => 'Internal response',
                                        'client-date' => 'Sun, 03 Sep 2017 00:32:11 GMT'
                                      }, 'HTTP::Headers' ),
                 '_content' => 'LWP will support https URLs if the LWP::Protocol::https module
is installed.
',
                 '_msg' => 'Protocol scheme \'https\' is not supported (LWP::Protocol::https not installed)',
                 '_rc' => 501
               }, 'HTTP::Response' );

WebEnv value not found in search output - WebEnv1 
Db value not found in fetch input
```

The problem isn't with my internet connection, because running `ping google.com` in the same container is successful. 

It seems like these images must be broken in some way, but I can't find the relevant code in this repo to troubleshoot.

**Comment by bgruening** [comment]
The error message says that https is not supported, if you try with a http URL is should work.

**Comment by bgruening** [comment]
@sminot can you tell me how you execute the container?

**Comment by osallou** [comment]
lwp::protocol:https is installed by conda recipe for runtime, program seems however not to find it.
Sample perl script shows the same error

    use LWP::UserAgent;
    use Data::Dumper;
    $ua = LWP::UserAgent->new(ssl_opts => { verify_hostname => 1 });
    $res = $ua->get("https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi");
    print Dumper($res);

Though file is present on system:

    ls /usr/local/lib/perl5/site_perl/5.22.0/LWP/Protocol/https.pm

**Comment by bgruening** [comment]
@osallou my assumption is that openssl or similar is missing in the container.

**Comment by osallou** [comment]
@bgruening seems indeed, it does not find Net::SSL module (and certainly some related libssl)
Seems package needs additional dependencies

**Comment by bgruening** [comment]
@osallou oh interesting. Where do you see this? Which package is missing Net:SSL?
This seems to pass the imports without it: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/perl-lwp-protocol-https/meta.yaml

**Comment by osallou** [comment]
I just added on above test script:

    use LWP::Protocol::https

and it shows:

    bash-4.2# perl test.pl 
    Can't load '/usr/local/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/auto/Net/SSLeay/SSLeay.so' 
    for module Net::SSLeay: libz.so.1: cannot open shared object file: No such file or directory at 
    /usr/local/lib/perl5/5.22.0/x86_64-linux-thread-multi/DynaLoader.pm line 193.
     at /usr/local/lib/perl5/site_perl/5.22.0/IO/Socket/SSL.pm line 19.
    Compilation failed in require at /usr/local/lib/perl5/site_perl/5.22.0/IO/Socket/SSL.pm line 19.
    BEGIN failed--compilation aborted at /usr/local/lib/perl5/site_perl/5.22.0/IO/Socket/SSL.pm line 19.
    Compilation failed in require at /usr/local/lib/perl5/site_perl/5.22.0/Net/HTTPS.pm line 27.
    Can't locate Net/SSL.pm in @INC (you may need to install the Net::SSL module) (@INC contains: 
    /usr/local/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.22.0 
    /usr/local/lib/perl5/5.22.0/x86_64-linux-thread-multi /usr/local/lib/perl5/5.22.0 .) at 
    /usr/local/lib/perl5/site_perl/5.22.0/Net/HTTPS.pm line 31.
    Compilation failed in require at /usr/local/lib/perl5/site_perl/5.22.0/LWP/Protocol/https.pm line 8.

**Comment by bgruening** [comment]
Huh, have you seen this?
```
for module Net::SSLeay: libz.so.1: cannot open shared object file: No such file or directory at 
```

**Comment by osallou** [comment]
yeap, libz.so.1 is needed by library but not found.
don't know if net/ssl is a fallback after ssleay failure, or it is a double error

**Comment by bgruening** [comment]
I have started something here: https://github.com/bioconda/bioconda-recipes/pull/5938
hopefully it fails and we can fix it :)

**Comment by bgruening** [comment]
libz should be included it is part of Net::SSLeay

**Comment by osallou** [comment]
yeap strange, but no libz.X found anywhere on system

**Comment by sminot** [comment]
The script I was using to test is as follows (from https://dataguide.nlm.nih.gov/edirect/install.html):

```
echo "***********************" > installconfirm
echo "esearch version:" >> installconfirm
esearch -version >> installconfirm
echo "xtract version:" >> installconfirm
xtract -version >> installconfirm
echo "EDirect install status:" >> installconfirm
esearch -db pubmed -query "Babalobi OO[au] AND 2008[pdat]" | \
efetch -format xml | \
xtract -pattern Author -if Affiliation -contains Medicine \
-element Initials >> installconfirm
echo "***********************" >> installconfirm
cat installconfirm
rm installconfirm
```
