### ISSUE TITLE
BEAST 'No such file'-error despite mapping

### ISSUE THREAD

**Issue by pragermh** [BioContainers/containers#179]
Hi,

I'm trying to use quay.io/biocontainers/beast:1.8.4--0 but it cannot find my input file (/home/maria/test.xml) although I have mapped my folder as suggested in the tutorial (http://biocontainers.pro/docs/101/running-example/):

`docker run -v /home/maria:/data/ quay.io/biocontainers/beast:1.8.4--0 beast test.xml`
gives error:
SEVERE: File error: test.xml (No such file or directory)

Any ideas on how to fix this?

Thanks.
/Maria

**Comment by sundeep-paulraj** [comment]
on general how do you run he beast command , can you please provide syntax of it ...

**Comment by osallou** [comment]
did you try "beast /data/text.xml" ?
and for mapping should be  -v /home/maria:/data (no trailing slash)

**Comment by pragermh** [comment]
Hi,

`docker run -v /home/maria:/data quay.io/biocontainers/beast:1.8.4--0 beast /data/test.xml`
did the trick, thanks.

The program now runs into problems with beagle, though:

> A fatal error has been detected by the Java Runtime Environment:
> SIGILL (0x4) at pc=0x00007fea685707a1, pid=9, tid=0x00007fea638fc700
> JRE version: OpenJDK Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
> Java VM: OpenJDK 64-Bit Server VM (25.102-b14 mixed mode linux-amd64 compressed oops)
> Problematic frame:
> C  [libhmsbeagle-cpu-sse.so.21.0.0+0x107a1]  beagle::cpu::EigenDecompositionCube<double, 2>::updateTransitionMatrices(int, int const*, int const*, int const*, double const*, double const*, double**, int)+0x231
> Core dump written. Default location: //core or core.9

(I have, however, installed a non-docker/biocontainer version of BEAST (and beagle) which work fine together)

/Maria
