### ISSUE TITLE
humann2 error 

### ISSUE THREAD

**Issue by brooksph** [BioContainers/containers#185]
Command used to produce error 
---
docker run -v /home/ubuntu/data:/data -it quay.io/biocontainers/humann2:0.6.1--py27_3 humann2 --input /data/SRR606249_subset10_1.trim30.fq.gz --output output --nucleotide-database /data/chocophlan --protein-database /data/uniref

Error message
---
Creating output directory: /output
Output files will be written to: /output
Decompressing gzipped file ...

CRITICAL ERROR: Can not call software version for diamond

I was going to try to debug this error myself but I can't find the dockerfile in this repo. Can you point me towards that?

**Comment by osallou** [comment]
@bgruening @brooksph , packaged version of diamond in humann2 is 0.8.36, but humann2 expects version 0.7.9 as defined in its code (config.py).
Furthermore, this release of diamond does not support the "*diamond -v*" option (now is *diamond version*) which is expecte by humann2 to check diamond license.

So it seems that humann2 needs to be package with diamond 0.7.9 as a hard requirement, or patched to remove version check (but may have impacts on other calls if options changed)

humann2 defines in its code:

    diamond_version={
      "flag" : "-v",
      "major" : 0,
      "minor" : 7,
      "second minor" : 9,
      "line" : 0,
      "column" : 1}

A bug should be raised in bioconda recipes for this tool.
