### ISSUE TITLE
Developer intro spelling error and a wrong link

### ISSUE THREAD

**Issue by slagelwa** [BioContainers/containers#186]
> 7) contribute If everything looks OK, you can contribute to the BioContainers project by sending us your **Docekerfile**. You can follow the instructions we have here, and after **ready**, your software will be available using the docker daemon fetch command.

Docekerfile should be Dockerfile, and the ready link goes to https://github.com/BioContainers/containers/blob/master/blast/2.2.31/Dockerfile

**Comment by ypriverol** [comment]
Thanks for reporting the issue, I have updated the code. Will be soon in the web version.
