### ISSUE TITLE
remove the sandbox repository.  

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/containers#189]
@prvst , @bgruening @osallou we should remove the sandbox repository. The sandbox was useful some time ago but it would be great if we keep only one repository the containers with the recipes and not both. If you agree with that I will remove it. 

Regards 
Yasset

**Comment by bgruening** [comment]
:+1:

**Comment by ypriverol** [comment]
@prvst @osallou @BioContainers/contributors ping

**Comment by prvst** [comment]
:+1:

**Comment by ypriverol** [comment]
@osallou are you ok to delete the sandbox

**Comment by osallou** [comment]
Yes
