### ISSUE TITLE
path order

### ISSUE THREAD

**Issue by baileyglen** [BioContainers/containers#196]
I am new to biocontainers. I was attempting to do some basic devlopment building off of your containers. I was attempting to install some python packages with conda, but the packages appear unavailable in python. I believe that this is due to the following lines..
ENV PATH=$PATH:/opt/conda/bin
ENV PATH=$PATH:/home/biodocker/bin

if I log into the container and do a "which python" I get 
/usr/bin/python
however "source activate" first gets me
/opt/conda/bin/python
which does have the installed packages.

Why does the base container not use ...

ENV PATH=/opt/conda/bin:$PATH
ENV PATH=/home/biodocker/bin:$PATH

**Comment by baileyglen** [comment]
It occurs to me that this leaves behind some of the other processing that a "source activate" would perform. Is there an example container already utilizing the python conda environment that I could look to for best practices?

**Comment by bgruening** [comment]
@prvst the base container has conda. The quay.io once do not have conda installed and no PATH conflict.

**Comment by bgruening** [comment]
@BaileyGlen welcome to BioContainers!

**Comment by baileyglen** [comment]
Sorry, still quite confused. Are there two different base images, once with conda, one without?

**Comment by bgruening** [comment]
@BaileyGlen no there is only one base image which you can use to write Dockerfiles compatible with biocontainers, but there are 3000 other containers that are completely auto generated out of conda packages ... so no base image exists and no Dockerfile.

This paper goes a little bit into the details: https://www.biorxiv.org/content/early/2017/10/11/200683
