### ISSUE TITLE
Version number on fastqc container listed as 0.11.15, but is 0.11.5

### ISSUE THREAD

**Issue by jason-weirather** [BioContainers/containers#197]
I see you are pulling 0.11.5 but the tag on these is labeled 0.11.15

https://hub.docker.com/r/biocontainers/fastqc/~/dockerfile/

```
ENV URL=http://www.bioinformatics.babraham.ac.uk/projects/fastqc/
ENV ZIP=fastqc_v0.11.5.zip
```

**Comment by osallou** [comment]
correct

* Directory on github should be renamed
* Dockerfile meta info should be updated
* Image should be rebuilt/tagged with correct version
* Container tag 0.11.15 should be removed

**Comment by jason-weirather** [comment]
Hi @osallou  just following up on this. I was hoping to recommend BioContainers as a resource with a bit better control on version tagging than other repositories to avoid duplicating some efforts. Any ETA on this, and is versioning in general a priority in BioContainers? 

Or is this something I could fix and do a pull request on?

**Comment by osallou** [comment]
Hi
Sorry, this bug was out of my mind with other stuff...
Biocontainers expects to be communatory, the guys in biocontainers do not expect to manage all bioinformatics software and updates by themselves, so definitly are accepting pull requests.

Anyway, i gonna fix this one.

**Comment by osallou** [comment]
I removed tagged container 0.11.15, 0.11.5 container is building

**Comment by jason-weirather** [comment]
Thanks so much @osallou !!
