### ISSUE TITLE
Container update: Kaiju

### ISSUE THREAD

**Issue by brooksph** [BioContainers/containers#199]
Hi -- I'm using the kaiju container and some recent updates to master include some useful functionality including gzip compatibility. Can you update the container to reflect these changes? @bgruening @luizirber

**Comment by bgruening** [comment]
@brooksph you are using this one? https://quay.io/repository/biocontainers/kaiju 
If so updating this recipe will give you a new container: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/kaiju/meta.yaml

**Comment by brooksph** [comment]
Yes, and thanks for the help @bgruening. Does the update require a new release? Although several changes were made to master the authors haven't cut a new release yet.

**Comment by bgruening** [comment]
Preferably we only create packages for releases. But exceptions can be made :-) are you going to update the recipe?

**Comment by brooksph** [comment]
Yep, I'll give it a shot.

**Comment by bgruening** [comment]
Cool thanks! Please ping me if you need help!
