### ISSUE TITLE
dDocent container broken

### ISSUE THREAD

**Issue by WallyL** [BioContainers/containers#201]
I have downloaded from Quay and tested several containers for this program (ver. 2.2.25--0 back to 2.2.8--0) and all fail to run due to a grep error:

grep: invalid option -- 'P'
BusyBox v1.22.1 (2014-05-23 01:24:27 UTC) multi-call binary.

It appears that the version of BusyBox used in the build employs an older version of grep that does not support the -P flag, which is required by dDocent.

**Comment by bgruening** [comment]
@WallyL grep does not seem to be defined as dependency, can you add it to the runtime deps here: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/ddocent/meta.yaml

**Comment by bgruening** [comment]
I added grep as dependency. The new container should have it.
