### ISSUE TITLE
fastqc permissions issue

### ISSUE THREAD

**Issue by samleenz** [BioContainers/containers#202]
Hi - I'm reasonably new to using docker / BioContainers so it is entirely possible the fault lies with me but I've been unable to get the container `biocontainers/fastqc` to work for me.

 This issue I'm having is that when I mount a volume `docker run -t -v <dir-name>:<dir-name> biocontainers/fastqc ...` fastqc starts running and is able to read+process the fastq files under `<dir-name>/raw` but then exits with an error message (below) when attempting to write results to `-o <dir-name>/fastqc/raw`. The output folder does exist however. 

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:312)
Caused by: java.lang.IllegalArgumentException: Output dir <dir-name>/fastqc/raw doesn't exist or isn't writeable
        at uk.ac.babraham.FastQC.FastQCConfig.<init>(FastQCConfig.java:51)
        at uk.ac.babraham.FastQC.FastQCConfig.<clinit>(FastQCConfig.java:26)
```

I then launched the container with a bash shell `docker run -it -v <dir-name>:<dir-name> biocontainers/fastqc bash` and found that I did not have permission to write files e.g. `touch test.txt` failed. 

I've now got fastqc working with a different docker image (`genomicpariscentre/fastqc`) but I would prefer to use the BioContainer one so any advice as to why this is not working for me would be much appreciated!

**Comment by osallou** [comment]
Hi,
By default biocontainers uses a non root user inside container to run
tools. So if directory already exists and is not world writable, then tools
will fail to write in bind mount volumes.
When adding volumes to container, chmod them before with 777, or launch the
container specifying the user option: --user root.

**Comment by samleenz** [comment]
Perfect - thanks. That's resolved the issue.

I had a feeling it was likely something simple like that!
