### ISSUE TITLE
wham container dependency missing

### ISSUE THREAD

**Issue by kmurphy902** [BioContainers/containers#204]
I am trying to use the wham container here: https://quay.io/repository/biocontainers/wham with this image:
quay.io/biocontainers/wham   1.7.0.311--0        32c1fc46467d        7 months ago        12.4MB

 When I try to run the wham or whamg command I get the following error:

`wham: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory`

It looks like that is missing from the image?

Thanks in advance,
Karyn

**Comment by bgruening** [comment]
Indeed, this recipes did not had any tests ... I try to fix this in https://github.com/bioconda/bioconda-recipes/pull/7578

**Comment by bgruening** [comment]
1.7.0.311--1 this version should now work! Thanks for using BioContainers.

**Comment by chapmanb** [comment]
Björn and Karyn;
Apologies about hacking this recipe and missing the issue. I appreciate the quick fix and help diagnosing the underlying problem.
