### ISSUE TITLE
quay.io/biocontainers/flash not available, although flash is in bioconda

### ISSUE THREAD

**Issue by pcm32** [BioContainers/containers#207]
On the bioconda page the container is even mentioned:

https://bioconda.github.io/recipes/flash/README.html

But if you go to: https://quay.io/repository/biocontainers/flash
is not available.

I thought I'd flag this up!

**Comment by bgruening** [comment]
@pcm32 flash recipe was added 2016 before we started to build containers and not updated since them.
I started an update here: https://github.com/bioconda/bioconda-recipes/pull/8043
Feel free to shime in. If this is merged the container will be created.

**Comment by bgruening** [comment]
Fixed.
