### ISSUE TITLE
Dockerfile for Profphd with wrong version of Perl

### ISSUE THREAD

**Issue by inaciomdrs** [BioContainers/containers#222]
I've used recently Dockerfile from profphd for using this tool, but when i run `docker run profphd prof`, an error message appears saying that Perl version must be < 5.16, but formed image by Dockerfile uses a version >= 5.16.

**Comment by osallou** [comment]
do you refer to containers/profphd/1.0.42-1-deb ?
this means that Debian package is not correct, abug report should be sent to debian for stretch.
I gonna submit bug to debian

**Comment by osallou** [comment]
@inaciomdrs , I have added Debian proposed patch to rnu profphd with more Perl release.
*prof* command run, but tool has not really been tested wit the patch.

You can however try to get docker profphd with tag v1.0.42-1-deb_cv2 to test the patched version.

If it works for you, debian would be welcomed to get a *real* test to validate patch.
