### ISSUE TITLE
Seqkit

### ISSUE THREAD

**Issue by suzuki-shm** [BioContainers/containers#223]
I'll request for Dockerfile with Seqkit.
It would be better to include pigz, accelerating parsing performance for gzipped data.

Repository: https://github.com/shenwei356/seqkit
Official page: http://bioinf.shenwei.me/seqkit/usage/

pigz: http://zlib.net/pigz/

**Comment by osallou** [comment]
@TaskeHAMANO  seqkit is available in bioconda at https://bioconda.github.io/recipes/seqkit/README.html  (container: https://quay.io/repository/biocontainers/seqkit) (without pigz it seems). This container is not ok for you?

**Comment by osallou** [comment]
@bgruening , seems seqkit recommends pigz dependency. Current conda recipe does not install it. Should we fill an issue to ask for pigz additional dependency?

**Comment by bgruening** [comment]
I ask @shenwei356 who is the developer of seqkit and maintainer of the conda recipe.

**Comment by bgruening** [comment]
@TaskeHAMANO can you try the latest image: https://quay.io/repository/biocontainers/seqkit?tab=tags

Thanks @shenwei356 for fixing!

**Comment by suzuki-shm** [comment]
Thanks @osallou and @bgruening !
