### ISSUE TITLE
The software folder should be one and the type of image / versioning a subfodler 

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/containers#226]
@osallou 

@bgruening has point me to the fact that each container version, for example, cutadapt has three different versions recipes depending on the python version. Can we move this into the following structure: 

tool/tool-version-flavour 

Regards 
Yasset

**Comment by osallou** [comment]
kinda cutadapt/1.0-py2 ?
you want to keep same structure as in bioconda

for debuian related imports, won't really be possible, as flavor is in package name, but I can see if I could diffentiate based on the format of the string.

**Comment by ypriverol** [comment]
@osallou 

> kinda cutadapt/1.0-py2 ? you want to keep same structure as in bioconda

This would be great honestly. Also, because is better to understand the repo. I don't want to do this at the level of the version but I support the idea that we should have a tool based folders for our users. Is less confusing for our end users. 

>for debuian related imports, won't really be possible, as flavor is in package name, but I can see if I could diffentiate based on the format of the string.

Please give priority to this because I don't think is good to have all the flavors in the root of biocontainers. Can you work on this?
