### ISSUE TITLE
Container request: breseq

### ISSUE THREAD

**Issue by yeemey** [BioContainers/containers#227]
I'm requesting a container for [breseq](https://github.com/barricklab/breseq), a variant-calling software designed for microbial ngs data. [breseq installation instructions are here.](http://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/installation.html)

Reference:
[Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations in laboratory-evolved microbes from next-generation sequencing data using breseq. Methods Mol. Biol. 1151: 165–188.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4239701/)

Thanks!

**Comment by osallou** [comment]
hi,
breseq is available as conda package and container:
https://bioconda.github.io/recipes/breseq/README.html
https://quay.io/repository/biocontainers/breseq

**Comment by yeemey** [comment]
Thank you! Only versions 0.29.0 and 0.31.1 are available in conda/container. Do I need new containers if I want to use different versions?
