### ISSUE TITLE
Trimmomatic Container Request

### ISSUE THREAD

**Issue by tushardave26** [BioContainers/containers#228]
Thanks so much for the containers. I would like to request a Docker container for [Trimmomatic](http://www.usadellab.org/cms/?page=trimmomatic) tool.

Thanks for your help.

**Comment by bgruening** [comment]
@tushardave26 here you go! https://quay.io/repository/biocontainers/trimmomatic?tab=tags

**Comment by tushardave26** [comment]
Thanks. That's quick. I do have one question though. Do the images on QUAY repo uses the similar Dockerfile as BioContainers? Can I just get the images directly from QUAY without creating an account?

**Comment by bgruening** [comment]
These containers are auto generated out of conda packages. You can get them without registration... Of course!

**Comment by tushardave26** [comment]
Thanks, @bgruening. I really appreciate your quick responses.

Best,
Tushar
