### ISSUE TITLE
quay image package manager

### ISSUE THREAD

**Issue by baileyglen** [BioContainers/containers#230]
I am currently working with quay.io/biocontainers/bioconductor-chippeakanno:3.12.0--r3.4.1_0. If I wanted to expand on this image, what package repository is available? For instance, for this specific package I need to install ghostscript. 
- apt-get, apt don't seem to be available
- conda commands are dead links to /opt/conda/bin/conda

**Comment by bgruening** [comment]
The is no package manager installed, however you could install miniconda3 into it if you want.
I guess the proper way would be to create a multi-package container with: https://github.com/BioContainers/multi-package-containers

**Comment by osallou** [comment]
An other option is to create a new docker image based on conda, install related conda package, then your needed packages, conda related or not
