### ISSUE TITLE
Extending existing HMMER3 image to include Easel mini applications

### ISSUE THREAD

**Issue by mscheremetjew** [BioContainers/containers#250]
Hello,
I am part of an Elixir project where we describe a new pipeline from scratch using the Common Workflow Language (CWL) including Docker hints, so we can run that pipeline on a cloud eventually. 

The aim is to re-use as many existing Docker images as possible to not waste any time on creating new images. In particular we are looking into BioContainers, because you've got plenty of images available.

Now I was looking for a Docker image including a set of tools called Easel - a library of C functions for biological sequence analysis. Easel (https://github.com/EddyRivasLab/easel) is not (yet) released on its own. It is part of the HMMER and Infernal releases. I've found a BioContainer HMMER3 image (biocontainers/hmmer:v3.1b2dfsg-5-deb_cv1), but unfortunately the default installation does not include the set of Easel mini applications, e.g. esl-reformat and so on.

Would be possible to extend the existing HMMER3 image to expose those Easel tools in addition?

Kind Regards,
Maxim

**Comment by osallou** [comment]
the hmmer:v3.1b2dfsg-5-deb_cv1 container is based on debian packages, so means the package 3.1b2 does not include those tools. On which hmmer3 are their included?

bioconda provides hmmer3.2 (https://bioconda.github.io/recipes/hmmer/README.html), is this release not ok?

**Comment by mscheremetjew** [comment]
Thanks for coming back to me. All HMMER 3 versions contain the Easel tools, but they are not installed by default at compile time, you would need to run an extra compilation step (page 13 of http://eddylab.org/software/hmmer3/3.1b2/Userguide.pdf)

I tried out bioconda including their Docker images (quay.io/biocontainers/hmmer:<3.2--0|3.1b2--3>) for version 3.1 and 3.2, but no luck.

I will try and see if I can extend the existing images. Do you want me to create a PR against you repo if I succeeded?

**Comment by osallou** [comment]
on biocontainers Dockerfile, you won't be able to extend it as it just
installs the debian package, no recompilation. But you could ask to conda
recipe to add extra compilation options (or do it yourself via a PR on
conda recipe)
