### ISSUE TITLE
mentalist: Permission denied when creating directory

### ISSUE THREAD

**Issue by dfornika** [BioContainers/containers#253]
I'm working on a CWL tool that uses the `quay.io/biocontainers/mentalist:0.1.8--0` container. When testing the tool in rabix-composer, I get the following error:

```
[INFO] Job root failed with exit code 1. with message: ERROR: LoadError: SystemError (with /usr/local/share/julia/site/lib): mkdir: Permission denied
```

I think that julia is trying to pre-compile some library code and write it to a directory under `/usr/local/share/julia/site/lib`. If I run the container directly on the command-line then login to it and run `mentalist -h` then the files are created as expected.

Is there some way to adjust the permissions on that directory in the container to make it writable?

**Comment by osallou** [comment]
Hi, i do not really understand.
You say that if you use container directly it works but not via cwl?

If you are root in container you can create what you want.

**Comment by dfornika** [comment]
Hi, thanks for replying. I've looked at this a bit more and I think the issue may be caused by the way that rabix-composer configures the container before running the test. I see this in my rabix-composer logs:

```
[INFO] Creating container with ContainerConfig: ContainerConfig{hostname=null, domainname=null, username=501:20, attachStdin=null, attachStdout=null, attachStderr=null, portSpecs=null, exposedPorts=null, tty=null, openStdin=null, stdinOnce=null,...
```

...so I'm thinking that I'll need to find a way to change that `username=501:20` configuration.

I don't think this is a problem with the container, so I'll close this issue.

**Comment by dfornika** [comment]
Actually, I have an idea. Is there any way that I can add a command to the Dockerfile for mentalist? As far as I know it's auto-generated from the bioconda build.

I'd just like to add one or two `RUN` statements that would trigger the pre-compilation of the julia `.ji` files when the image is created. Then the they won't be written when the container is run because they will already exist.

**Comment by osallou** [comment]
Updating conda recipe would update container too.
If it is a matter of precompiling some things it would make sense.





Le jeu. 5 juil. 2018 à 01:26, Dan Fornika <notifications@github.com> a
écrit :

**Comment by dfornika** [comment]
Ok, I'll give that a try.

**Comment by dfornika** [comment]
I've tried leaving the pre-compiled files in the bioconda build, but unfortunately it breaks the package, presumably because the `.ji` files are built against a specific machine configuration, so they can't be easily copied from one machine to another.

I think it would be fine to package up the pre-compiled files in the docker container, since that should be a reproducible environment. If there is a way to create a slightly different build for the docker container then I'd like to try that.
