### ISSUE TITLE
Base image and python3

### ISSUE THREAD

**Issue by ghost** [BioContainers/containers#256]
I  had to add the following to the base image to get python3 working

```USER root RUN apt-get update && \
apt-get install -f --reinstall -y python3 && \
apt-get clean && \
apt-get purge && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

Is that a bug?

**Comment by osallou** [comment]
Wel, base image is a *base* only, python3 is not a default in all distrib releases.
If you need python3 for something, you should extend image and add indeed python3.

**Comment by ghost** [comment]
Indeed, but Py2.7 is deprecated, isn't not worth taking that to the account?

**Comment by ghost** [comment]
My other concern is why I had to force reinstall `-f --reinstall` python3 is that not a bug?

**Comment by osallou** [comment]
@ypriverol should base image be updated to a more recent version with python3

regarding install options, well this is related to distro...

**Comment by pcm32** [comment]
My two cents is that base image includes too many things, I would go for a rather leaner base image, if at all. Why do I want python for R package related containers for instance...

**Comment by ghost** [comment]
@pcm32 I believe base image is for those who needs to run tools that may need more then just python and having entire OS makes sense. If you run Python or R script you should use Python or R container, rather than base image :)

**Comment by ypriverol** [comment]
@ola-t this is only true if the containers are not based on that image and I guess we have a lot of containers based on that image. @osallou can we review that.? 

The @pcm32 point is that all the containers we generate should be based on the a slim base image. (**Size should be important**)

**Comment by pcm32** [comment]
Agreed, the point in biocontainers is to make containers for single tools, is rare that a tool requires everything that is on our base image. If we want to keep the concept of base images, I would suggest having different flavours for the different needs (r-base, python2-base, python3-base, conda-base), instead of having a single monolithic and heavy base image. This of course comes at a maintenance burden.

**Comment by osallou** [comment]
If user needs additional packages, he can extend the tool image to adds required packages.
I do not know what was the initial purpose to add those packages in base image
