### ISSUE TITLE
biopython download error

### ISSUE THREAD

**Issue by mchiapello** [BioContainers/containers#257]
I run the follow command:

`docker pull biocontainers/biopython`

I got the follow message:

`Error response from daemon: manifest for biocontainers/biopython:latest not found`

Am I doing somenthing wrong?

> Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

**Comment by osallou** [comment]
you should specify the tag you need, *latest* tag is usually not available. For reproducibility you should specify a version

**Comment by mchiapello** [comment]
Thank you for the quick reply! 

How do I specify the tag/version?

**Comment by osallou** [comment]
for example:

    docker pull biocontainers/biopython:v1.68dfsg-3-deb-py3_cv1.1114

**Comment by osallou** [comment]
seems there is an issue though. for biopython, a latest tag exists, and even specifying release does not work. I am having a look

**Comment by osallou** [comment]
should be:

    docker pull containers.biocontainers.pro/biocontainers/biopython:your_tag

**Comment by osallou** [comment]
in fact, seems some containers are not present on dockerhub, don't know why

containers.biocontainers.pro contains our "backup" containers, so you can access them here, but they  **should** be on dockerhub. We are investigating why they are not present

**Comment by osallou** [comment]
ok, works now, don't know if there was a temp pb or if I did something wrong...
anyway:

    # https://hub.docker.com/r/biocontainers/biopython/tags/
    docker pull biocontainers/biopython:v1.68dfsg-3-deb-py3_cv1

**Comment by mchiapello** [comment]
Thank you! 👍
