### ISSUE TITLE
Dockerfile for Salmon

### ISSUE THREAD

**Issue by michael-kotliar** [BioContainers/containers#261]
How can I be sure that the version of Salmon installed in this [Dockerfile](https://github.com/BioContainers/containers/blob/master/salmon/0.7.2ds1-2b1-deb/Dockerfile)
corresponds to `0.7.2ds1-2b1-deb`?
Why `sudo apt-get install <package name>=<version>` is not used?

**Comment by osallou** [comment]
A specific label is put, it maps to the package version when container was
built (package version info is added in container labels)

Olivier

Le dim. 19 août 2018 à 16:55, Michael Kotliar <notifications@github.com> a
écrit :
