### ISSUE TITLE
Container for bedtools 2.27

### ISSUE THREAD

**Issue by davidmasp** [BioContainers/containers#266]
I think there is already a bioconda package for the new version of bedtools (2.27) -  see [here](https://anaconda.org/bioconda/bedtools). Could the 2.25 container be updated to the newer version?

**Comment by osallou** [comment]
Debian generated can't be upgrade as dependent from debian packages.
However feel free to upgrade version from non debian based dockerfiles if
needed.

However, if bioconda versionbis available, its container too .

Olivier

Le dim. 26 août 2018 à 04:40, David Mas-Ponte <notifications@github.com> a
écrit :

**Comment by davidmasp** [comment]
Hi again, thanks for the quick response.

I am pretty noob to biocontainers and containers in general, what do you mean versionbis? I understand [this container](https://github.com/BioContainers/containers/blob/master/bedtools/2.26.0dfsg-3-deb/Dockerfile) needs the debian repos to update the package first. For the conda docker though I think it can be done. Are you favouring debian containers against conda in general?

I tested with the existing Dockerfile for bedtools 2.25 (this one [here](https://github.com/BioContainers/containers/blob/master/bedtools/2.25.0/Dockerfile)) just changing this [line](https://github.com/BioContainers/containers/blob/4937f09f5e1c832ba3b7fad0fedd269c4e253c7e/bedtools/2.25.0/Dockerfile#L22) to 

```
RUN conda install bedtools=2.27.0
```

and it installs the latest version.

**Comment by osallou** [comment]
We do not favor any, just taking any viable source of open source software.
Debian is one of those source and containers are automatically created from
debian repo. Conda is an additional one.

From, 2.25, changing version as well as label version do the job indeed.
You just need to create a new version directory like the 2.25 one , update
version related fields and do a pull request.

Le dim. 26 août 2018 à 13:11, David Mas-Ponte <notifications@github.com> a
écrit :

**Comment by davidmasp** [comment]
Okay, will do.

Thanks

**Comment by davidmasp** [comment]
Great! Thanks for merging the PR

**Comment by osallou** [comment]
Thanks for doing the job ;-)

Le dim. 26 août 2018 à 23:02, David Mas-Ponte <notifications@github.com> a
écrit :
