### ISSUE TITLE
picard needs the CLASSPATH environment variable to point to its jar file 

### ISSUE THREAD

**Issue by mr-c** [BioContainers/containers#269]
`picard` needs the `CLASSPATH` environment variable to point to its jar file (`/usr/local/share/picard-2.9.2-2/picard.jar`

This enables running Picard commands in a generic way without having to reference the specific path
See https://github.com/heliumdatacommons/cwl_workflows/pull/2/files#diff-7a3b58a11d174bf793aac51b043735b4 for the motivation

**Comment by bgruening** [comment]
Hi @mr-c, which container are you using?

**Comment by mr-c** [comment]
Hey @bgruening I'm using `quay.io/biocontainers/picard:2.9.2--2`

https://github.com/heliumdatacommons/cwl_workflows/pull/2/files#diff-7a3b58a11d174bf793aac51b043735b4R22

**Comment by bgruening** [comment]
So this container is created by conda pkgs, you would need to fix the conda pkg. In this case I think you are just using it wrong. You should just call a `picard` wrapper. And not `java ....`.

**Comment by mr-c** [comment]
The recommended way to run `MarkDuplicates` is via `java` so that java memory options can be set
http://broadinstitute.github.io/picard/command-line-overview.html#UsageExample

I guess I can use `JAVA_TOOL_OPTIONS` environment variable to set the memory options and use the `picard` script in the container: https://github.com/heliumdatacommons/cwl_workflows/pull/3

Thanks!
