### ISSUE TITLE
Adding the AWS CLI to containers

### ISSUE THREAD

**Issue by sminot** [BioContainers/containers#270]
Question: Would it be reasonable for me to issue PRs adding the AWS CLI (or other cloud provider CLIs) to various BioContainer images?

Motivation: I would like to use the BioContainers docker images directly for my analysis, but my ideal workflow would have those containers being executed on some cloud resource, such as AWS. In order to execute those analyses on the cloud, files must be fetched from some storage resource (such as AWS S3) and results must be returned to that resource. That process is made much easier if there is a working copy of the AWS CLI (e.g.) in the Docker image.

Example: Nextflow supports AWS Batch, but requires that all Docker images have the AWS CLI installed (ref: https://www.nextflow.io/docs/latest/awscloud.html#aws-batch).

**Comment by osallou** [comment]
Hi,
This is not a good idea. Aws cli is one tool, but there are azure, gcp etc... 
Furthermore, container must be limited to a tool. Addibg more tools around would add size, more surface attack and more tools to update in a same container

For you workflow, you should execute aws cli to fetch data, then call container tool and call cli again to push. Aws cli could be itself in a awscli container.
A shell wrapper could just do the aws stuff around the tool call.

**Comment by osallou** [comment]
Concerning nextflow, aws in container is nit a requirement, and not even
recommended way:

The aws tool can either be included in container image(s) used by your
pipeline execution OR installed in a custom AMI that needs to used in place
of the default AMI when configuring the Batch Computing environment.

The latter approach is preferred ..  :-)

**Comment by sminot** [comment]
Ah, that's a great point. It would be a lot better to put it into the AMI. Thanks for taking the time to respond!
