### ISSUE TITLE
Documentation to run GUI?

### ISSUE THREAD

**Issue by robert-winkler** [BioContainers/containers#274]
Hi, how can the GUI of DenovoGUI be started on an Ubuntu system? 
>docker run biocontainers/denovogui QUITS WITHOUT ERROR
>docker run -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix biocontainers/denovogui ENTERS AN INTERACTIVE SESSION: biodocker@c9f52ce7c61a:/data$ 
Best, Robert

**Comment by ypriverol** [comment]
@prvst you have experience running UI system for some softwares. Can you help here.

**Comment by osallou** [comment]
not specifiy to biocontainers but to docker in general, there is indeed no display by default in containers.
Additional params are needed as you specified

    docker run -ti --rm \
           -e DISPLAY=$DISPLAY \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
          biocontainers/my_tool

    # my_tool_command

once in container you need to specify the command to execute, there is no default entry point in container if you look at container.
so in your case *my_tool_command* is denovogui

**Comment by robert-winkler** [comment]
Would these parameters also work on a Windows/MacOS workstation?

**Comment by osallou** [comment]
I don't know...

Le jeu. 20 sept. 2018 à 16:17, Robert Winkler <notifications@github.com> a
écrit :

**Comment by prvst** [comment]
I have done some tests in the past but I'm not that of an expert. I know that this command works for the compomics tool but it doesn't work for TOPPAS, for example. It seems that the command will depend on the tool requirements.
