### ISSUE TITLE
containers from quay.io not in the internal repo

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/containers#275]
This containers from quay.iohttps://quay.io/repository/biocontainers/gnu-wget?tab=tags 

is not found in the elixir internal repo 

https://containers.biocontainers.pro/v2/biocontainers/gnu-wget/tags/list

**Comment by osallou** [comment]
Quay.io containers are built from bioconda.
Pulling all conda containers would be quite huge task, and would beed a
full scan...

**Comment by osallou** [comment]
We may also face name/version conflicts

Le dim. 23 sept. 2018 à 08:42, olivier sallou <olivier.sallou@gmail.com> a
écrit :

> Quay.io containers are built from bioconda.
> Pulling all conda containers would be quite huge task, and would beed a
> full scan...
>
>
>
> Le sam. 22 sept. 2018 à 18:35, Yasset Perez-Riverol <
