### ISSUE TITLE
Some Dockerfiles (e.g., bwa) are out of date compared to quai.io and Bioconda

### ISSUE THREAD

**Issue by kyleabeauchamp** [BioContainers/containers#283]
I was in a docker for bio tutorial and someone pulled some images from biocontainers, but they were out of date.  Looking more closely, the Dockerfiles have not been synced with the available packages on Bioconda and containers on quai.io.  For example:

```
docker pull biocontainers/bwa
docker pull quay.io/biocontainers/bwa:0.7.17--ha92aebf_3

docker run biocontainers/bwa bwa 2>&1 | head -n 3
docker run quay.io/biocontainers/bwa:0.7.17--ha92aebf_3 bwa 2>&1 | head -n 3

Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.15-r1140

Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.17-r1188
```

**Comment by ypriverol** [comment]
Please, We recommend you to switch your containers to use the quay.io versions unless you want to really use the Dockerfile-based ones. The conda-based containers are also maintained by the biocontainers community.
