### ISSUE TITLE
Installations to /tmp break cwltool invocation via Docker

### ISSUE THREAD

**Issue by drjrm3** [BioContainers/containers#284]
The [FastQC Dockerfile](https://github.com/BioContainers/containers/blob/master/fastqc/0.11.5/Dockerfile)  installs the program to /tmp and then symlinks to `/usr/local/bin`. When run with `cwltool` (which overrides `/tmp`), the CWL workflows are unable to find the executables.

Can the installation be performed in a more standard location and leave `/tmp` for truly temporary work?

**Comment by osallou** [comment]
This is indeed a bad idea to install in /tmp as it is a temporay directory.. Needs fix
