### ISSUE TITLE
Biocontainer for EGA-CRG/EOSC-Pilot project

### ISSUE THREAD

**Issue by pditommaso** [BioContainers/containers#286]
We would need to deposit a Biocontainer for the EOSC-Pilot pipeline developed by the EGA and CRG organisations. 

Project pipeline is host at [CRG-CNAG/EOSC-Pilot](https://github.com/CRG-CNAG/EOSC-Pilot) GitHub repo. 

The Docker images is deposited in the Docker hub with this ID: 

```
cbcrg/eosc-pilot@sha256:4eecb3beb062e81a2efa7737ee2b4d04b4417ec0d678001776857e9dbc2c050f
```

The image was build using this [Docker file](https://github.com/CRG-CNAG/EOSC-Pilot/blob/master/docker/Dockerfile). 

cc @NinoSpataro

**Comment by osallou** [comment]
your dockerfile could be easilly added, you just need via a PR to add your dockerfile in a repository with your softwarename/version

and adding to dockerfile some labels according to our specs https://github.com/BioContainers/specs/blob/master/container-specs.md

as this is a pipeline and not a single tool, you would just need to set software name with a name of your choice representing your pipeline

**Comment by pditommaso** [comment]
Nice! Though not sure to understand the difference between `LABEL version` and `LABEL software.version` ?  

Note: this is a multi tool container.

**Comment by osallou** [comment]
software.version directly relates to your software/pipeline

version relates to the Dockerfile itself, for example if you change something in your dockerfile but the software is the same (to fix a directory, add a package; ....)

**Comment by pditommaso** [comment]
Clear. Thanks!

**Comment by pditommaso** [comment]
See #289

**Comment by osallou** [comment]
Closed with PR

**Comment by pditommaso** [comment]
Where exactly the biocontainer image is deposited and how to recover it? I've tried to look for it in the [registry](https://biocontainers.pro/registry/) but I'm getting a "server error" message.

**Comment by osallou** [comment]
web server is currently under devpt/refactoring, leading to errors/inconsistencies... (@ypriverol web server shows no container at all (nor any warning for user))

You can always check on Docker hub anyway for an image/tag:

https://hub.docker.com/r/biocontainers/eosc-pilot/tags/

**Comment by pditommaso** [comment]
Nice, thanks.
