### ISSUE TITLE
porechop confused with seqan

### ISSUE THREAD

**Issue by sjackman** [BioContainers/containers#287]
This is a rather unusual issue. All the tags for the repository porechop are actually for seqan.
https://quay.io/repository/biocontainers/porechop?tab=tags
There is no repository for seqan.
https://quay.io/repository/biocontainers/seqan

**Comment by osallou** [comment]
@bgruening ?
this is a bioconda related package

**Comment by sjackman** [comment]
That was a fast response! I was confused. The version number of `porechop` does in fact contain the string `seqan`.
See https://github.com/bioconda/bioconda-recipes/blob/e8c19ecb7e2d7a0d61ce63a4bda499eb0f457b3e/recipes/porechop/meta.yaml#L7
Sorry for the noise.
