### ISSUE TITLE
bandage: could not find or load the Qt platform

### ISSUE THREAD

**Issue by sjackman** [BioContainers/containers#288]
The `bandage` container fails with the following error.
```sh
docker pull quay.io/biocontainers/bandage:0.8.1--hb59a952_0
docker run --rm quay.io/biocontainers/bandage:0.8.1--hb59a952_0 Bandage --version
```
```
This application failed to start because it could not find or load the Qt platform plugin "minimal"
in "".

Available platform plugins are: minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
```

**Comment by sjackman** [comment]
This issue has been reported upstream as well.
See https://github.com/bioconda/bioconda-recipes/pull/10785
and https://github.com/bioconda/bioconda-recipes/pull/6492
and https://github.com/rrwick/Bandage/issues/22
and https://github.com/rrwick/Bandage/issues/8
and possibly related https://github.com/ContinuumIO/anaconda-issues/issues/1182

**Comment by sjackman** [comment]
The Qt5 plugin `minimal` is located at `/usr/local/plugins/platforms/libqminimal.so`
It looks as though Qt is having trouble finding it. I don't what the search path is for this file.

**Comment by sjackman** [comment]
I've found the root cause, which is a missing library `libXrender.so.1`.
```
❯❯❯ QT_DEBUG_PLUGINS=1 Bandage --version
…
QLibraryPrivate::loadPlugin failed on "/usr/local/plugins/platforms/libqminimal.so" : "Cannot load library /usr/local/plugins/platforms/libqminimal.so: (libXrender.so.1: cannot open shared object file: No such file or directory)"
❯❯❯ ldd /usr/local/plugins/platforms/libqminimal.so | grep 'not found'
	libXrender.so.1 => not found
❯❯❯ ls /usr/lib/libXrender* /usr/local/lib/libXrender*
ls: cannot access /usr/lib/libXrender*: No such file or directory
ls: cannot access /usr/local/lib/libXrender*: No such file or directory
❯❯❯ apt-get update && apt-get install libxrender1
…
❯❯❯ Bandage --version
Version: 0.8.1
```
🎉

To which repo and against which file do I open a PR to resolve this issue?

**Comment by ypriverol** [comment]
Please if you are using the conda recipe. It will be solved in the conda side.

**Comment by sjackman** [comment]
Hi, Yasset. The Conda formula for Bandage works, but the Biocontainer `quay.io/biocontainers/bandage` does not work (see above). It requires the `libxrender1` package to be installed by `apt-get`. As far as I know, this library is not available via Conda. Since the base image of Biocontainers includes X11, it seems to me it should also include the package `libxrender1`.

**Comment by ypriverol** [comment]
Should we create a recipe as Dockerfile for this case @osallou ?
