### ISSUE TITLE
:latest docker-image is not updated

### ISSUE THREAD

**Issue by jgriss** [BioContainers/containers#294]
Even though a new version of the spectra-cluster-cli tool was added to BioContainers, the `:latest` image in docker hub was not updated.

Can anyone tell me how these `:latest` images are created?

**Comment by osallou** [comment]
There is no latest tag, you should use the specific generated tag
We do not add latest because latest means last build, not last version

**Comment by jgriss** [comment]
At least for the spectra-cluster-cli container a :latest tag was created and pushed to docker hub.

This is also true for several other Biocontainer containers. Since docker by default pulls the ":latest" version this is quite misleading.

I'd argue that the ":latest" containers should be removed from docker hub.

**Comment by osallou** [comment]
Before container auto builds, some containers were pushed to docker hub,
reason why a few have latest tag

Le ven. 2 nov. 2018 à 13:02, Johannes Griss <notifications@github.com> a
écrit :

**Comment by jgriss** [comment]
This is fine but since they are not updated and per-default regarded as the newest version, I'd argue they still should be removed.

**Comment by osallou** [comment]
removed for spectra-cluster-cli, will have to check others

**Comment by osallou** [comment]
@Raynooo we need to find all biocontainers containers on hub with a latest tag to remove them

**Comment by jgriss** [comment]
@osallou Thanks a lot!

**Comment by Raynooo** [comment]
We now have a script ( **BioContainers/backup-scripts/find_latest_tags/find_latest_tags.py** ) that searches every repo in our dockerhub and creates a list of all those who have an image tagged as _latest_
Right now there are 106 tools in this list, I'll get rid of those images.

**Comment by Raynooo** [comment]
Images that were tagged as "latest" which were actually not the latest images have been deleted.
A couple of images still are tagged latest but those only have the one image so it makes some sense.

**Comment by osallou** [comment]
I suppos you kept ci related tags which of course have latest tag

**Comment by Raynooo** [comment]
Yes, both Jenkins related images and a few more images are in this situation, here's the list:

- jenkins_version
- jenkins_spec_check
- ddi-web-app
- nmrpro
- container-mtbls-dwnld
- phnml-jupyter
- nmrglue
