### ISSUE TITLE
Parameters not properly processed in many dockerfiles

### ISSUE THREAD

**Issue by jgriss** [BioContainers/containers#298]
This issue is found in several Dockerfiles (using the MSGFPlus one as example):

The "MSGFPlus" shell script is created using the following statement in the Dockerfile: 
```
bash -c 'echo -e "#!/bin/bash\njava -jar /home/biodocker/bin/MSGFPlus_9949/MSGFPlus.jar $@" > /home/biodocker/bin/MSGFPlus' && \
```

In the actual container the `$@` which passes on the command line parameters is missing. The solution to this is to escape the `$@` by using single quotes and remove the `bash -c` command as it is not required anyways:

```
echo -e '#!/bin/bash\njava -jar /home/biodocker/bin/MSGFPlus_9949/MSGFPlus.jar $@' > /home/biodocker/bin/MSGFPlus && \
```

The exact same statement is used in several docker files, so it probably affects many images.

**Comment by osallou** [comment]
@Raynooo can you have a look?

**Comment by Raynooo** [comment]
On it

**Comment by Raynooo** [comment]
I'm guessing the original recipe used _bash -c_ to ensure _echo -e_ was called correctly, without it the echo command prints _-e #!/bin/bash_ on the first line. _echo $_ has the same problem and a simple _echo_ won't cut it. Looking for a fix.

**Comment by Raynooo** [comment]
Simply escaping the \$@ seems to work, the dockerfile line ends up being:
`bash -c "echo -e '#!/bin/bash\njava -jar /home/biodocker/bin/MSGFPlus_9949/MSGFPlus.jar \$@' > /home/biodocker/bin/MSGFPlus" && \`

**Comment by jgriss** [comment]
Whether you use the single quote or escape the `$@` has the same effect. If you use single quotes you don't have to escape any special characters which could be beneficial for more complex scripts.

**Comment by Raynooo** [comment]
As said in the previous message, somehow when using only _echo -e '...'_ this is what's in the final image's _msgfp_ bin:
```
-e #!/bin/bash
java -jar /home/biodocker/bin/MSGFPlus_9949/MSGFPlus.jar $@
```
Where the shebang is prefixed by _-e_
