### ISSUE TITLE
10xgenomics/cellranger

### ISSUE THREAD

**Issue by anton-khodak** [BioContainers/containers#304]
Hi,

I would like to ask for a container for a `cellranger` tool.

Repository (support for building and running is not provided): https://github.com/10XGenomics/cellranger 
Binaries: https://support.10xgenomics.com/single-cell-gene-expression/software/downloads/latest
Information about the software: https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/what-is-cell-ranger

**Comment by osallou** [comment]
@Raynooo could you please have a look at this tool?

**Comment by Raynooo** [comment]
I'm on it

**Comment by Raynooo** [comment]
I have an issue with Licenses, since the open source version available on github still requires another version of Ranger (2.1.0) that's not open source itself...

**Comment by Raynooo** [comment]
I have made some tests and cellranger 2.1.1 can be **built** but not run without installing _Ranger 2.1.0_ first.
Installing this package is free but can **not** be made anonymously (ie: 10X provides a temporary link if you give an email address but this link cannot be used in a recipe as it would expire pretty quickly and would be linked to someone's email address).
I've tried removing all dependencies to _Ranger_, hoping only open-source bioinformatics tools would be sufficient but they are not. Accordingly this container/image can not be built by us, sorry.

**Comment by anton-khodak** [comment]
Thank you, @Raynooo ! By the way, if you tried to make a Dockerfile, could you please share your version?

**Comment by Raynooo** [comment]
Of course, here it is (I've added some comments explaining what I would do if I find a workaround).
(I had to add a .txt extension to the Dockerfile so github would accept it)

[Dockerfile.txt](https://github.com/BioContainers/containers/files/2772934/Dockerfile.txt)

**Comment by anton-khodak** [comment]
Thank you a lot! We'll need to host our own Docker image for this tool basing on yours one. I guess the issue can be closed now.
