### ISSUE TITLE
Error in bracken container

### ISSUE THREAD

**Issue by josmos** [BioContainers/containers#305]
Image: quay.io/biocontainers/bracken:2.2--py27h2d50403_1

Running the bracken-build script gives the following error:
` >> Creating database125mers.kmer_distrib 
      ERROR: kmer2read_distr program not found. 
          Run 'sh install_bracken.sh' to generate the kmer2read_distr script.
          Alternatively, cd to BRACKEN_FOLDER/src/ and run 'make'
`
kmer2read_distr is installed under /usr/local/bin/, but taking a look at the kraken-build script, reveals it should be installed in $DIR/src/kmer2read_distr, (DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )")

**Comment by osallou** [comment]
this is based on a bioconda package, @bgruening ?

**Comment by josmos** [comment]
Sorry if this is not the right place for this issue. Where should I post it?

**Comment by osallou** [comment]
no pb :-)

https://github.com/bioconda/bioconda-recipes/issues
