### ISSUE TITLE
Missing ps tool in multiqc Biocontainer image

### ISSUE THREAD

**Issue by pditommaso** [BioContainers/containers#308]
AFAIK Biocontainer images are expected to be created using busybox as base image, however it seems the some basic tools included in busybox as not available. For example 

```
docker run   quay.io/biocontainers/multiqc:1.6--py35h24bf2e0_0 sh -c 'ps'
sh: 1: ps: not found
```

Why `ps` is not included in the above container ?

**Comment by osallou** [comment]
Hi,
this is an image built from bioconda (@bgruening ).
bioconda based containers contain only the tool itself, no "extra" system related package.

Those from biocontainers repo are ubuntu based, containing more utilities, but resulting in larger container size.

**Comment by pditommaso** [comment]
I know that it's an image build from bioconda. Since they are merged in the biocontainers channel I was expecting that's the right place to report this issue.

**Comment by bgruening** [comment]
@pditommaso multiqc uses click and this needs to have some very strange UTF-8 locales included which is not part of busybox as a consequence the tests fail. So bioconda has decided to offer an alternative base image for those packages.

You can see this in the recipe here: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/multiqc/meta.yaml#L134

The problems seem to be that this base image, an ubuntu, does not have `ps`?
Thats an issue on the Bioconda side, can you please open an issue there and discuss the extended_base image?

**Comment by osallou** [comment]
@pditommaso  If you need access for debug,.., you can create a new container image, conda based, and install the conda package.
