### ISSUE TITLE
Container request: portcullis

### ISSUE THREAD

**Issue by maplesond** [BioContainers/containers#309]
I'm struggling to build portcullis 1.1.2 directly as a bioconda package, however I have working instances already in dockerhub: maplesond/portcullis:1.1.2.  Github repo is here: https://github.com/maplesond/portcullis.  Can this be added as a biocontainer and then turned into a bioconda package?

**Comment by osallou** [comment]
I do not understand
this is already a bioconda package (https://bioconda.github.io/recipes/portcullis/README.html)
If you only want to upgrade the release, then you should go to bioconda repo and do a PR to update release. A container will then be automatically created.

**Comment by maplesond** [comment]
Yes, it was a bioconda package as of 1.1.1.  Since then I suspect there must have been significant changes to the bioconda c++ build tools as 1.1.2 no longer builds.  To get 1.1.2 as a bioconda package I thought going via containers might be a less painful process.

**Comment by maplesond** [comment]
So I guess what I asking is that because I already have a Dockerfile that works well with portcullis for V1.1.2.  Is it possible to register this as a biocontainer and then use that container in a bioconda package?  I got the impression from the biocontainers paper that this is possible but possibly I've misunderstood something: https://academic.oup.com/bioinformatics/article/33/16/2580/3096437

**Comment by osallou** [comment]
you cannot go from a container to a bioconda package, only from bioconda to container.

you could do a PR (using our rules) to create a container, but this will not create a conda package.

**Comment by maplesond** [comment]
That's a bit unfortunate though as it doesn't seem possible (or at least straightforward) to build our software using the bioconda tool stack at the moment.  Thanks for your help though and for clarify that point.  I'll see if there's something we can do on the bioconda side to fix the build.
