### ISSUE TITLE
Cpat container not found on docker hub

### ISSUE THREAD

**Issue by rhpvorderman** [BioContainers/containers#311]
#310 was merged and added a container for cpat. But I cannot find it on docker hub. Is the build not automated? Is there any verification that needs to pass?

**Comment by osallou** [comment]
it is available:

https://hub.docker.com/r/biocontainers/cpat/tags

there is no "latest" tag you must specify the needed tag version

**Comment by rhpvorderman** [comment]
Sorry. My bad. I couldn't find the repo with the docker hub search function and it did not work with tag '1.2.4'. Sorry for the inconvenience. Thank you for the fast answer!
