### ISSUE TITLE
bedtools CMD removal/update?

### ISSUE THREAD

**Issue by vortexing** [BioContainers/containers#322]
I'd gladly use the bedtools docker container but can't b/c of the `CMD` line.  Any chance of taking that out so others can use it in different ways?

https://github.com/BioContainers/containers/blob/master/bedtools/2.27.0/Dockerfile

Also, there's a v2.28 now:  https://github.com/arq5x/bedtools2/releases

**Comment by osallou** [comment]
Regarding CMD what is your issue, it can be overriden. Cmd is only a default, but is overriden is you specify some args to docker run, like a 

    docker run biocontainers/bedtools bedtools -h

Regarding new version, we will have a look, but feel free to do a PR to upgrade a tool

**Comment by osallou** [comment]
bedtools 2.28 is building

**Comment by vortexing** [comment]
Thanks for 2.28.  However, I'm trying to use this in context of a workflow manager and I can't provide a command to override the CMD, plus the CMD "bedtools" is not actually required to be run so why prescribe it?  The choice makes several of the biocontainers containers not work for people using certain workflow managers without figuring out how to trick the workflow manager.  Just my 2 cents.

**Comment by osallou** [comment]
For 2.28 i set entrypoint
Entrypoint can be overiden with the -entrypoint option.
Cmd is usually overriden simply setting expected cmd after the docker run imagename.

Many containers (not only biocontainers) provider entrypoints/args to provide some defaults. Up to user to soecify other calls if needed.

So all depends on tools using containers to provide a way to specify the command to use and override the defaults of the container.


In a 'real world' a tool cannot expect containers not to specify an entrypoint

Entryppint/cmd are only defaults... Not constraints on usage.

**Comment by osallou** [comment]
I would personally put none, but this not a requirement by itself, and community maintained.
Some people find it useful to get direct tool access.

If this is really a constraint against other tools we may discuss to propose not setting any entrypoint/cmd in dockerfiles but would be nice to get non opiniated tools on container definition.

@ypriverol, some suggestions?

**Comment by vortexing** [comment]
So if I'm understanding correctly, the community consensus is agnostic to CMD/ENTRYPOINT (which seems fine - no sense in being overly confining), but in order to save many people a few characters of text (the word "bedtools", it makes the containers unusable for people using workflow managers without a hack?  I absolutely love the idea and work behind biocontainers, but I'm bummed to realize that I often won't be able to leverage everyone's hard work! Maybe I'll stumble upon a different solution!?

**Comment by osallou** [comment]
As i said, many containers in registries make use of this, so why do workflow tools expect not getting any? It is as simple as specifying the entrypoint on cmd line.. And works in all cases...


Anyway, I'd be glad to remove any entrypoint/cmd in biocontainers, as a requirement, if others agree with that.

**Comment by osallou** [comment]
@vortexing we have removed CMD and ENTRYPOINT from most of containers (for their latest versions for now)

**Comment by vortexing** [comment]
That's cool!  Thank you.  

BTW, workflow managers appear to be built for managing a lot of workflow chaos, and thus they have their own way of setting up and defining jobs.  While it seems to humans "as simple as specifying" something on the command line, it's actually not that simple in the context of a workflow manager (likely depends on the specific workflow manager as well!). The idea of workflow manager developers trying to take into account users using docker containers from any possible source, with any sort of structure at all seems overwhelming and out of scope.  

Making things more general, but well documented seems like a great way to go for those of us on this side of things, and I appreciate your effort in making it so!!
