### ISSUE TITLE
suggest to remove entrypoint/cmd from Dockerfile

### ISSUE THREAD

**Issue by osallou** [BioContainers/containers#323]
Some tools try to run Docker with a cmd line
This create an issue when there is an entrypoint or cmd defined in Dockerfile

It can be workaround specifying the entrypoint option, but all tools are not using it.

As most bio tools define only the main binary and not a whole default command, it is of little use.

I suggest to remove them from existing containers and in specifications not to set them

**Comment by osallou** [comment]
@ypriverol @bgruening your opinion?

**Comment by bgruening** [comment]
The automatic created containers do not set any of those, so fine by me :)

**Comment by osallou** [comment]
Cf discussion in #322

**Comment by osallou** [comment]
Removed entrypoint/cmd from containers (latest releases only)
