### ISSUE TITLE
bedops is missing samtools

### ISSUE THREAD

**Issue by da-i** [BioContainers/containers#330]
When running bam2bed  in quay.io/biocontainers/bedops:2.4.23--0 it trows an error that there is no samtools binary present in the container:

<code>docker run -ti -v /local/bam/dir:/bams quay.io/biocontainers/bedops:2.4.23--0 bash
bash-4.2# bam2bed < some.bam > test.bed</code>

<code>
Error: Cannot find samtools binary required for conversion of BAM and SAM format
convert2bed
  version:  2.4.23
  author:   Alex Reynolds
....</code>

**Comment by osallou** [comment]
this is a bioconda container, created from conda package.
I think you should create an issue in bioconda package.
@bgruening ?

**Comment by bgruening** [comment]
Check out the new container with build-number 1. It should have samtools installed. Please feel free to reopen.
