### ISSUE TITLE
spades does not work

### ISSUE THREAD

**Issue by jjkoehorst** [BioContainers/containers#331]
The spades located in: https://github.com/BioContainers/containers/blob/master/spades/3.6.0/Dockerfile does not work.

At startup it shows a `Exception caught basic_string::_S_construct null not valid`. Maybe the binaries are pre-compiled for the wrong os?

**Comment by osallou** [comment]
Indeed, seems to download precompiled files, bad idea...
Will have to compile from source or fibd working bin
