### ISSUE TITLE
container request: sratools

### ISSUE THREAD

**Issue by nsheff** [BioContainers/containers#337]
I was unable to find a container for [sratools](https://github.com/ncbi/sra-tools). Is this the right place to post a container request?

**Comment by osallou** [comment]
Hi,
Yes this is the place.
There is already sra-tools: https://quay.io/repository/biocontainers/sra-tools

You can look at available tags at https://biocontainers.pro/#/tools/sra-tools

**Comment by nsheff** [comment]
got it. I missed it because of the hyphen. sorry!
