### ISSUE TITLE
kraken1.1.1 tar invalid option z

### ISSUE THREAD

**Issue by aaguinal** [BioContainers/containers#353]
I am trying to build the Kraken standard database using the image `quay.io/biocontainers/kraken:1.1.1--pl526hc9558a2_3` and it seems that this BusyBox tar version does not support unzipping `*.tar.gz` (e.g. `taxdump.tar.gz`).

and the command:
 `docker run quay.io/biocontainers/kraken:1.1.1--pl526hc9558a2_3 kraken-build --standard --db kraken_db`

I am getting an error that says:
```
Untarring taxonomy tree data... tar: invalid option -- 'z'
BusyBox v1.22.1 (2014-05-23 01:24:27 UTC) multi-call binary.

Usage: tar -[cxthvO] [-X FILE] [-T FILE] [-f TARFILE] [-C DIR] [FILE]...

Create, extract, or list files from a tar file

Operation:
        c       Create
        x       Extract
        t       List
        f       Name of TARFILE ('-' for stdin/out)
        C       Change to DIR before operation
        v       Verbose
        O       Extract to stdout
        h       Follow symlinks
        exclude File to exclude
        X       File with names to exclude
        T       File with names to include
```

**Comment by osallou** [comment]
Hi,
This is a conda based container, you should create an issue at bioconda. This pb will occur also on non container installs where such tar issue occurs, could be worth to send this issue upstream too as they depend on exterbal tool that may not do the job depebding on install os.


Maybe package should depend on an other tar tool? Or require some compression lib to make it work.

@bgruening , an idea?

**Comment by bgruening** [comment]
Yes tar is not compiled with `z` option. If this tool needs tar then we need to depend on it.

**Comment by aaguinal** [comment]
Thanks for the reply and the rapid commit! Do you know how often they rebuild the docker images? I want to know when this change will be available using biocontainer.

**Comment by osallou** [comment]
once commited, it goes though continuous integration which manages also docker build, so should be ready soon.
