### ISSUE TITLE
Debian based biocontainer for VG

### ISSUE THREAD

**Issue by mr-c** [BioContainers/containers#360]
https://tracker.debian.org/pkg/vg

Thanks!

**Comment by osallou** [comment]
Hi, our ci system is not yet fully fonctional due to maintenance work at ebi cloud (and certainly covid related delays...)

Would do once system is back...

**Comment by mr-c** [comment]
@osallou  Good to know! I made a PR: https://github.com/BioContainers/containers/pull/361
