### ISSUE TITLE
Spingo images are 0.00MB

### ISSUE THREAD

**Issue by aaguinal** [BioContainers/containers#364]
I think images don't exist... Docker image size is 0.00M 
https://biocontainers.pro/#/tools/spingo

**Comment by osallou** [comment]
This is a conda based image, and show no description either. Did you try to pull image to see if image or web site display info?
 @bgruening , a container generation issue?

**Comment by bgruening** [comment]
Spingo does not compile, see here: https://github.com/bioconda/bioconda-recipes/pull/9458

**Comment by bgruening** [comment]
Any help welcome.

**Comment by bgruening** [comment]
Its now online here: https://quay.io/repository/biocontainers/spingo?tab=tags
