### ISSUE TITLE
skewer tool with gzipped input

### ISSUE THREAD

**Issue by lucacozzuto** [BioContainers/containers#374]
Dear developers,
I tried to run the container quay.io/biocontainers/skewer:0.2.2--1 for using skewer on gzipped input files but I got this error that is likely related to the version of gzip.

```
  gzip: unrecognized option '--rsyncable'
  BusyBox v1.22.1 (2014-05-23 01:24:27 UTC) multi-call binary.
```

Can you help me on this, please?

Luca

**Comment by osallou** [comment]
Seems indeed that package makes use of a specific gzip version or compilation option.
Issue is on conda side, @bgruening ?

**Comment by bgruening** [comment]
@lucacozzuto you need to add gzip2 as runtime dependency to https://github.com/bioconda/bioconda-recipes/blob/master/recipes/skewer/meta.yaml I think.

**Comment by lucacozzuto** [comment]
something like this? should make a pull request?

```
requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - gzip2
  ```

**Comment by bgruening** [comment]
@lucacozzuto i think it is

```
  run:
    - bzip2
```

**Comment by lucacozzuto** [comment]
thanks! I just did it

**Comment by lucacozzuto** [comment]
Hi all, it looks like is not yet solved. Can you help me on this, please?

**Comment by osallou** [comment]
Hi,
as it is a conda issue, please fill an issue at https://github.com/bioconda/bioconda-recipes
