### ISSUE TITLE
sra-tools repository is missing curl dependency

### ISSUE THREAD

**Issue by nsheff** [BioContainers/containers#376]
fastq-dump requires curl, but the sra-tools container doesn't contain it, so fastq-dump can't run:

The container I'm using is: quay.io/biocontainers/sra-tools:2.10.0--pl526he1b5a44_0 

Here's what you get:
```
docker run --rm --init \
  --workdir="`pwd`" \
  quay.io/biocontainers/sra-tools:2.10.0--pl526he1b5a44_0 fastq-dump SRX5974995
```

no curl in PATH at /usr/local/bin/fastq-dump line 608.

**Comment by osallou** [comment]
This is a conda based container, coumd you please an issue at https://github.com/bioconda/bioconda-recipes

Once conda package is fixed, container will be automatically updated with a new fix version

**Comment by bgruening** [comment]
I guess this is fixed? Please reopen if not. Thanks!

**Comment by nsheff** [comment]
I believe it was, thanks @bgruening
