### ISSUE TITLE
Bowtie2 needs python3

### ISSUE THREAD

**Issue by osallou** [BioContainers/containers#377]
`bowtie2-build` lacks python3 on the latest docker hub images

**Comment by ayedaemon** [comment]
is this still open?

**Comment by osallou** [comment]
Yeap 😉
I am on holidays and will check this once back.
However, anyone can submit a pull request to fix the issue....

**Comment by ayedaemon** [comment]
Can you check and let me know if anything is left for this issue.

**Comment by ayedaemon** [comment]
Why is it still open?

**Comment by osallou** [comment]
because commit did not specify close of this issue...
