### ISSUE TITLE
container request: colomoto-docker

### ISSUE THREAD

**Issue by pauleve** [BioContainers/containers#378]
Hi,
The CoLoMoTo Docker project https://github.com/colomoto/colomoto-docker ships Docker images  distributing multiple tools related to biological network modeling with Jupyter integration.
I'm wondering how we could make it fit in BioContainers infrastructure.

**Comment by osallou** [comment]
Copying their dockerfile abd addibg a few metadata (origin link, license etc.) would do the job.
However, seems it builds a container with lots of tools inside, not a very good practice and will certainly lead to very large image

**Comment by pauleve** [comment]
I agree the objectives and purpose of these images are quite different from BioContainers.
