### ISSUE TITLE
container request: AutoClassWeb

### ISSUE THREAD

**Issue by pierrepo** [BioContainers/containers#379]
Dear BioContainers community,

I would like to know if you will accept to host Docker images for AutoClassWeb.

AutoClassWeb is a web application that eases the use of Autoclass C Bayesian clustering algorithm. The project is already on GitHub (https://github.com/pierrepo/autoclassweb) under BSD 3-clause license.

I already have a working [Dockerfile](https://github.com/pierrepo/autoclassweb/blob/master/Dockerfile) that I could adapt to BioContainers requirements. So far, the Docker image size is about 1.2 GB.

**Comment by osallou** [comment]
Hi, simply fork, add a dockerfile following ours specs (if possible use our base image, but not mandatory) and add expected labels to dockerfile and ask to merge your updates
