### ISSUE TITLE
singularity for biocontainers/bowtie2 

### ISSUE THREAD

**Issue by moldach** [BioContainers/containers#382]
I'm able to pull/build `deepvariant` from DockerHub with singularity doing the following:

```
singularity build deepvariant.simg docker://google/deepvariant
```

However, trying the same for[ `bowtie2` from DockerHub is not working]?(https://hub.docker.com/r/biocontainers/bowtie2):

```
singularity build bowtie2.simg docker://biocontainers/bowtie2
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: Error reading manifest latest in docker.io/biocontainers/bowtie2: manifest unknown: manifest unknown
(base) [moldach@arc IGV_Linux_2.8.9]$ singularity build bowtie2.simg biocontainers/bowtie2  FATAL:   Unable to build from biocontainers/bowtie2: unable to open file biocontainers/bowtie2: open biocontainers/bowtie2: no such file or directory
```

**Comment by osallou** [comment]
Biocontainers containers do not have a latest tag, you must specify the tag you want

**Comment by moldach** [comment]
Thank you I see that I can use the following link for tags: https://quay.io/repository/biocontainers/bowtie2?tab=tags
