### ISSUE TITLE
container request: deepgoplus

### ISSUE THREAD

**Issue by coolmaksat** [BioContainers/containers#384]
Dear BioContainers community,

We would like to make our software DeepGOPlus available for
to bioinformatics community. Source code and dockerfile
is available at https://github.com/bio-ontology-research-group/deepgoplus/.

Could you please help us to publish it. Thank you.

**Comment by osallou** [comment]
Hi, 
You only need to fork repo and create a PR with your dockerfile in your software/version directory.
Please follow our *specs* for your dockerfile (see doc on web site).
You can see other tools as examples in our repo

**Comment by coolmaksat** [comment]
Thank you. Done.
