### ISSUE TITLE
r-minionqc lacks locale data needed for readr dependency

### ISSUE THREAD

**Issue by mjmansfi** [BioContainers/containers#390]
First, I apologize if this is not the correct place to file an issue. I am reporting on the `1.4.2--r40_0` [image found here](https://quay.io/repository/biocontainers/r-minionqc). 

`minionqc` uses the `readr` package, which looks for locale information that is missing from the container. For example (with `3005e42f599f` in the example being the image ID of the `quay.io/biocontainers/r-minionqc:1.4.2--r40_0` image):

```
mjmansfield@Luscombe-Precision-3630-Tower:test$ docker run -it 3005e42f599f 
/ # printf "a,b,c,d\n1,2,3,4\n"
a,b,c,d
1,2,3,4
/ # printf "a,b,c,d\n1,2,3,4\n" > thing
/ # R

R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-conda_cos6-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(readr)
> a <- read_csv('thing')
Error: Unknown TZ UTC
In addition: Warning message:
In OlsonNames() : no Olson database found
> 
```

The simple fix is to add `tzdata` library to the `Dockerfile` (but I cannot find this in the repo). See: https://github.com/tidyverse/readr/issues/952

**Comment by osallou** [comment]
Hi,
This a container based on bioconda package, you should submit issue on bioconda side

**Comment by mjmansfi** [comment]
Hello, 

Is that true? The conda installation shouldn't actually require the `tzdata` package, since normally a conda install will exist on top of an operating system that already has that locale data (i.e., `tzdata` is already present). It's in the context of docker that it must be specified and installed manually, as pointed out in the issue I linked. 

If you could point me to the r-minionqc `Dockerfile` I can try building an image with and without that library to confirm this.

Best regards,
Mike

EDIT: clarity

**Comment by osallou** [comment]
bioconda based containers are not built with a Dockerfile but automatically generated from conda package.
this occured for several other containers conda based.

**Comment by mjmansfi** [comment]
Hello, 

I see. I'm not really sure how to address this in that case.

Should I request the maintainers of the `r-minionqc` conda package add `tzdata` to their environment, even though it's really only necessary in the context of a docker container (I mean, I guess it _is_ a prerequisite, just one that is not necessary to specify in most cases)?

Best regards,
Mike

**Comment by osallou** [comment]
you should create an issue on bioconda github site with the issue details, don't know if they add tzdata as requirement or specific stuff for container build

**Comment by mjmansfi** [comment]
Hello,

Sure thing. Thanks for your help!

Best regards,
Mike
