### ISSUE TITLE
Accessing bwa mem inside docker. 

### ISSUE THREAD

**Issue by kghimire09** [BioContainers/containers#393]
Hi biodocker team, 
I am building a fastq to vcf pipeline using bwa, gatk and picard tools. I implemented your code for docker image for bwa, gatk and picard. For bwa I used
 From biocontainers/biocontainers:latest
The metadata
Installation
RUN conda install bwa=0.7.15. 
Now that issue I have is how do I run the bwa commands to build my script? I need to use bwa mem command. Same with gatk and picard. Please could you help me?
Thank you

**Comment by osallou** [comment]
Why do you build a container with all tools and not simply call in your script each tool container?

I do not really understand your issue. If you conda installed bwa etc... when running your container you should just need to call executable names in your docker run

**Comment by bgruening** [comment]
Please let us know if you have still problems. Closing for now.
