### ISSUE TITLE
relocate fastqc executable for the fastsqc container

### ISSUE THREAD

**Issue by didillysquat** [BioContainers/containers#398]
The fastqc executable inside the biocontainers/fastqc:v0.11.9_cv7 container is currently located at `/home/biodocker/bin/fastqc`.

This location is causing issues due to automatic binding of the user's home directory on some systems (i.e. HPC systems) when using Singularity. This means that the fastqc executable cannot be found when running with default binding.

Of course this can be worked around with custom binds but its not an ideal solution.

Could the executable rather be located in `/usr/bin/` or `/usr/local/bin`?

Many thanks!

**Comment by osallou** [comment]
Thanks for analysis, will be better indeed to do so.
Issue certainly occurs in others containers

Will fix this one
