### ISSUE TITLE
Container request: ConoDictor

### ISSUE THREAD

**Issue by Ebedthan** [BioContainers/containers#400]
Dear BioContainers team,

I would like to kindly request a BioContainer for ConoDictor. ConoDictor is available at https://github.com/koualab/conodictor. It has already a Dockerfile that could facilitate this request. 

Looking forward to your response.

Regards.

**Comment by osallou** [comment]
build in progress

**Comment by Ebedthan** [comment]
Great! Thanks.

**Comment by osallou** [comment]
by the way your dockerfile version is not aligned with your latest version

**Comment by osallou** [comment]
built, should appear in registry next week (cron task) , but container is available biocontainers/conodictor:v2.2.2_cv1

**Comment by Ebedthan** [comment]
Thanks again. I have updated the version of the Dockerfile.
