### ISSUE TITLE
container upgrade request: mothur

### ISSUE THREAD

**Issue by didillysquat** [BioContainers/containers#401]
Hi there,

Thanks for your work.

Would it be possible to upgrade the biocontainer's mothur image to a new version. The 1.41 version you currently have available has some annoying bugs in the make.contigs command where mothur breaks when trying to make contigs directly from gzipped fastq files.

An upgrade to either 1.44.3 or 1.45.0 would be appreciated.

Thanks so much.

**Comment by osallou** [comment]
Hi,
feel free to create a pull request to update it ;-)

Else will need to wait for a team member time to manage it

**Comment by osallou** [comment]
current mother container is based on Debian package, which is still v1.41. Need debian release will add v1.44
If you need a more recent version , then a specific mothur install (from source) is needed

**Comment by didillysquat** [comment]
@osallou . Apologies for the delay. Thanks for the update. I imagine v1.44 would be helpful for most users. Due to time constraints, in the end, I modified an [existing very simple docker image](https://github.com/HadrienG/dockerfiles/blob/master/mothur/Dockerfile) to get the job done. This is the contents of the docker image. Feel free to make use of it if it makes life easier.

```
FROM ubuntu:groovy-20210225

MAINTAINER Benjamin Hume <didillysquat@gmail.com>

RUN apt-get update && apt-get -y install wget unzip && \
    wget https://github.com/mothur/mothur/releases/download/v.1.45.0/Mothur.Ubuntu_20.zip && \
    unzip Mothur.Ubuntu_20.zip && \
    rm Mothur.Ubuntu_20.zip && \
    rm -rf __MACOSX

#adds executables to the path
ENV PATH /mothur:$PATH
```

**Comment by bgruening** [comment]
We have here also some recent containers: https://quay.io/repository/biocontainers/mothur?tab=tags

Hope that helps!
Bjoern
