### ISSUE TITLE
samtools: no Perl in the container, tools fail to run

### ISSUE THREAD

**Issue by lgorenstein** [BioContainers/containers#403]
Looks like Samtools containers is missing Perl, so many installed tools fail to run (`blast2sam.pl`, `bowtie2sam.pl`, etc):

```
$ singularity run https://depot.galaxyproject.org/singularity/samtools:1.9--h10a08f8_12 blast2sam.pl
WARNING: Skipping mount /var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
env: can't execute 'perl': No such file or directory
```

Hopefully an easy fix, right?

**Comment by osallou** [comment]
Hi, this container is built from bioconda package, so if perl is needed, issue should be created on conda package (which will fix the container...)

Thanks

**Comment by lgorenstein** [comment]
Thank you Olivier, created an issue there.

**Comment by bgruening** [comment]
Commented upstream.
