### ISSUE TITLE
Requesting gmap biocontainer for version 2021.05.27

### ISSUE THREAD

**Issue by tamuanand** [BioContainers/containers#407]
Hi

I would like to request a gmap biocontainer for version 2021.05.27 using http://research-pub.gene.com/gmap/src/gmap-gsnap-2021-05-27.tar.gz

Please note - The Biocontainers registry has gmap version 2021.03.08 - https://biocontainers.pro/tools/gmap and this version has fatal bugs as identified by the authors athttp://research-pub.gene.com/gmap/

Given below is my Dockerfile if I were to build this on my own
```
FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y build-essential wget
RUN wget http://research-pub.gene.com/gmap/src/gmap-gsnap-2021-05-27.tar.gz -O /tmp/gmap-gsnap.tar && \
        tar -xvf /tmp/gmap-gsnap.tar && \
        rm /tmp/gmap-gsnap.tar -f
RUN     cd gmap-2021-05-27 && \
        ./configure && \
        make && \
        make install
```

Thanks

**Comment by osallou** [comment]
Hi, maybe you could submit a pull request with dockerfile, simply adding requested labels, based on other containers examples and doc?
Else we we will consider your request, but with summer holidays, it may take some time.

Thanks

**Comment by osallou** [comment]
If you are familiar with dockerfile, a multi stage build would enable to build tool, and in second stage copy built tool, to limit container size (avaiding gcc, wget etc. in container)

**Comment by tamuanand** [comment]
Hi

I am not comfortable with multi-stage build and I would like a container with a smaller size. The size using my dockerfile is about 500 MB and that's the reason I submitted the issue here requesting your help

Please advise.

**Comment by tamuanand** [comment]
One other piece of info: The bioconda gmap package is update and shows version = 2021-05-27

https://anaconda.org/bioconda/gmap

**Comment by osallou** [comment]
If bioconda package is uptodate then container is available.

Biocontainers registry website is only updated once a week, so if package is recent it may not appear. But it should appear on bioconda website

**Comment by osallou** [comment]
https://quay.io/repository/biocontainers/gmap?tab=tags

**Comment by ypriverol** [comment]
The container is in the registry https://biocontainers.pro/tools/gmap
