### ISSUE TITLE
Add poppler-utils container

### ISSUE THREAD

**Issue by mciprianoCDC** [BioContainers/containers#409]
Poppler-utils allows conversion of pdf files to text files, as well as other pdf manipulation types of operations. This allows manipulation of pdf files from reports generated from some other biocontainer sofware. Here is a dockerfile based on alpine which is very small which allows the following operations:

/usr/bin/pdf2dsc 
/usr/bin/pdf2ps 
/usr/bin/pdfattach 
/usr/bin/pdfdetach 
/usr/bin/pdffonts 
/usr/bin/pdfimages 
/usr/bin/pdfinfo 
/usr/bin/pdfseparate 
/usr/bin/pdfsig 
/usr/bin/pdftocairo 
/usr/bin/pdftohtml 
/usr/bin/pdftoppm 
/usr/bin/pdftops 
/usr/bin/pdftotext 
/usr/bin/pdfunite

##########################################################################
FROM alpine:3.4
LABEL base_image="poppler-utils:v0.43.0"
LABEL version="1"
LABEL software="poppler-utils"
LABEL software.version="0.43.0"
LABEL about.summary="PDF utilities (based on Poppler)"
LABEL about.home="https://poppler.freedesktop.org/"
LABEL about.documentation="https://poppler.freedesktop.org/"
LABEL about.license_file="https://poppler.freedesktop.org/"
LABEL about.license="SPDX:GPL-2.0-only"
LABEL extra.identifiers.biotools="poppler-utils"
LABEL about.tags="poppler-utils"

################## MAINTAINER ######################
MAINTAINER Michael Cipriano <mcipriano@gmail.com>

RUN apk add --no-cache poppler-utils

#############################################################################

**Comment by osallou** [comment]
Hi,
You put a biotools entry in your dockerfile, but cannot find any.

I am not fond of putting this tool in biocontainers, it is not *bio* related but a general purpose tool.
