### ISSUE TITLE
Container request: metaplatanus

### ISSUE THREAD

**Issue by rkajitani** [BioContainers/containers#410]
This is about [MetaPlatanus](https://github.com/rkajitani/MetaPlatanus), a de novo metagenome assembler.
I created the PR for Bioconda, and it was merged two weeks ago.
This tool is now available in Bioconda but seems to be missing in Biocontainers.
What should I do to register it to Biocontainers?

Bioconda info and recipe:
https://bioconda.github.io/recipes/metaplatanus/README.html
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/metaplatanus

**Comment by osallou** [comment]
Hi, maybe a registry website sync issue. Registry is updated once a week, but if conda cobtainer was created 2 weeks ago, it should appear

@ypriverol could you check registry status?
