### ISSUE TITLE
Docker image registry update

### ISSUE THREAD

**Issue by pierrepo** [BioContainers/containers#413]
Dear BioContainer maintainers

Could you indicate me how often the Docker image registry is updated? Is it triggered automatically once the PR is merged? Do I have to perform myself an extra step?
The new version for [autoclassweb](https://github.com/BioContainers/containers/pull/412) has been merged, but I can't see the new Docker image in its corresponding [registry](https://biocontainers.pro/tools/autoclassweb).

Many thanks for your help.

**Comment by osallou** [comment]
Web site is updated once a week (friday i think but not sure)

However, container itself is available short time after merge (time for rebuild and push)

**Comment by osallou** [comment]
On dockhub you should find available container and tags

**Comment by pierrepo** [comment]
Many thanks @osallou 
The issue looks the same on [DockerHub](https://hub.docker.com/r/biocontainers/autoclassweb/tags). The image from the last PR does not appear.

**Comment by osallou** [comment]
There was indeed a push error, i am trying to fix this

**Comment by osallou** [comment]
Container should be available now

**Comment by pierrepo** [comment]
Yep :tada: 
Many thanks for your help @osallou
