### ISSUE TITLE
Alien Hunter Can't locate FindBin.pm

### ISSUE THREAD

**Issue by mmfacun** [BioContainers/containers#424]
Hello.

After pulling alien hunter docker image, and running it, i got this message:

> Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/alien_hunter/alien_hunter.pl line 38.
BEGIN failed--compilation aborted at /usr/share/alien_hunter/alien_hunter.pl line 38.

Please help. Thank you.

**Comment by osallou** [comment]
hi,
which container are you using?

**Comment by mmfacun** [comment]
hi. I'm running alien hunter from this
`docker pull biocontainers/alien-hunter:v1.7-7-deb_cv1`

**Comment by mmfacun** [comment]
please check out my log after running the alien hunter docker image:

![image](https://user-images.githubusercontent.com/89125684/137700423-73e97e69-c456-4fbf-9ddf-834b916a66d4.png)
@osallou

**Comment by osallou** [comment]
yeap I found the issue, I am fixing it (an issue with original debian package)

**Comment by osallou** [comment]
biocontainers/alien-hunter:v1.7-7-deb_cv2 should be available with missing lib

**Comment by mmfacun** [comment]
Thank you. It's working now.
