### ISSUE TITLE
Some important containers to be created

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/containers#47]
- [x] ProteoWizard
- [x] SpectraST
- [x] Fido
- [x] Percolator

**Comment by prvst** [comment]
added proteowizard

**Comment by prvst** [comment]
spectraST is part of TPP, should we create a separate container for it ?

**Comment by ypriverol** [comment]
I guess comet also and still has its own container. 

Sent from my Samsung device

-------- Original message --------

**Comment by prvst** [comment]
yes that's true, what I meant was that SpectraTS is shipped as part of TPP,
I'm not sure if we can download the software as an independent binary, like
comet is.

**Comment by ypriverol** [comment]
I guess should be possible to pack it outside.

**Comment by mvaudel** [comment]
Hi guys!

I need to deploy and use [PennCNV](http://penncnv.openbioinformatics.org/en/latest/) on our clusters here. This involves some fun with Perl and dependencies. Would it make sense to make a Biocontainer (or, to call it the German way, Biotonne)?
I was thinking it is a good way to try the submission and deposition system by newbies not very good with a computer (like me)?

@ypriverol sorry, missed you yesterday, but would be nice to have a chat one of these days :)

**Comment by ypriverol** [comment]
Hi Marc, 100% in the direction of making the docker container. Please let us know if you need any help. I'm now working in the docker registry that will make more visible all of our containers. Marc, Harald is also trying to make SearchGUI and peptideShacker works in Biodocker. Please, give a hand to him. 

We can talk or chat where ever you want. 

Regards 
Yasset

**Comment by mvaudel** [comment]
Yes we have been working on having SearchGUI and PeptideShaker compatible but thought you were happy with our latest improvements?

**Comment by ypriverol** [comment]
See this https://github.com/BioDocker/biodocker/issues/45

**Comment by prvst** [comment]
SpectraST is available via TPP container
Fido is available via Crux container
Proteowizard and Percolator were added last month
