### ISSUE TITLE
bowtie2

### ISSUE THREAD

**Issue by ghost** [BioContainers/containers#57]
Hi, on BioDocker there is currently a containter for "biodckr/bowtie" (v.1.1.2)(https://hub.docker.com/r/biodckr/bowtie/).    Are there plans to create a container for bowtie2 (v.2.2.9)(http://bowtie-bio.sourceforge.net/bowtie2/index.shtml)?  Bowtie and bowtie2 are really two separate applications; it would be very helpful to have a container for bowtie2.

**Comment by ypriverol** [comment]
Hi @rmc7777:
 Thanks for reporting it. I will create the corresponding issue in Sandbox repo and feel free to contribute. 
 If not one of our contributors will try to create it for you.

**Comment by ypriverol** [comment]
https://github.com/BioDocker/sandbox/issues/68
