### ISSUE TITLE
samtools

### ISSUE THREAD

**Issue by qw1mb0** [BioContainers/containers#62]
Hi.
I have some problem with run containter:
`$ docker run -v /root/test/:/data/ samtools '/usr/local/bin/samtools view -F 4 -Sb /data/tuberculosis.sam > /data/tuberculosis.bam'`

I got errors:

```
exec: "/usr/local/bin/samtools view -F 4 -Sb /data/tuberculosis.sam > /data/tuberculosis.bam": stat /usr/local/bin/samtools view -F 4 -Sb /data/tuberculosis.sam > /data/tuberculosis.bam: no such file or directory
Error response from daemon: Cannot start container b63e8e4b2cffe04579b5d7caff8a8a71ff9eb3627f7b9b03ad076ae250c98b4d: [8] System error: exec: "/usr/local/bin/samtools view -F 4 -Sb /data/tuberculosis.sam > /data/tuberculosis.bam": stat /usr/local/bin/samtools view -F 4 -Sb /data/tuberculosis.sam > /data/tuberculosis.bam: no such file or directory
```

Can you, please, explain what am u doing wrong?
But when i run simple samtools it's work fine:
`$ docker run -v /root/test/:/data/ samtools '/usr/local/bin/samtools`

```
Program: samtools (Tools for alignments in the SAM format)
Version: 1.2 (using htslib 1.2.1)

Usage:   samtools <command> [options]

Commands:
  -- indexing
         faidx       index/extract FASTA
         index       index alignment
  -- editing
         calmd       recalculate MD/NM tags and '=' bases
         fixmate     fix mate information
         reheader    replace BAM header
         rmdup       remove PCR duplicates
         targetcut   cut fosmid regions (for fosmid pool only)
  -- file operations
         bamshuf     shuffle and group alignments by name
         cat         concatenate BAMs
         merge       merge sorted alignments
         mpileup     multi-way pileup
         sort        sort alignment file
         split       splits a file by read group
         bam2fq      converts a BAM to a FASTQ
  -- stats
         bedcov      read depth per BED region
         depth       compute the depth
         flagstat    simple stats
         idxstats    BAM index stats
         phase       phase heterozygotes
         stats       generate stats (former bamcheck)
  -- viewing
         flags       explain BAM flags
         tview       text alignment viewer
         view        SAM<->BAM<->CRAM conversion
```

**Comment by qw1mb0** [comment]
I'm create folder **/root/test** with input files run docker with parametr **-v /root/test:/data/** but got error. But if i create on host system folder /data/ and copy input files on host system to folder **/data**. Run docker:
`$ docker run -v /root/test/:/data/ samtools '/usr/local/bin/samtools view -F 4 -Sb /data/tuberculosis.sam > /data/tuberculosis.bam'`
This is take input files from host system folder **/data**, but not from **/data/** in container. And output copy to host system **/data/** folder.

**Comment by prvst** [comment]
Hi @qw1mb0 

I noticed that you are using simple quotes around the command:

`'/usr/local/bin/samtools view -F 4 -Sb /data/tuberculosis.sam > /data/tuberculosis.bam'`

is this how you should be running your program? have you tried without the quotes?

**Comment by qw1mb0** [comment]
Problem in character ">" becasue system run this command on host system, not in container and output write to host system file. Can I push this full command to run on docker container?

**Comment by prvst** [comment]
it should execute that inside the container, lets try this: 
1. delete the current container you have on your mahcine
2. run `docker pull biodckr/samtools`
3. Try to execute the program again, but this time call the container biodckr/samtools and dont worry about using the full path inside the container (/usr/local/bin/samtools), just call for samtools, like this:

`docker run -v /root/test/:/data/ biodckr/samtools samtools` and the rest of your params

**Comment by sauloal** [comment]
The problem is that, by using quotes, bash is trying to run the whole text as if it was the name of the command.

to do as you wish, prepend the command with bash -c

e.g.:

`$ docker run -v /root/test/:/data/ samtools bash -c '/usr/local/bin/samtools view -F 4 -Sb /data/tuberculosis.sam > /data/tuberculosis.bam'`
