### ISSUE TITLE
Cleaning Base Image

### ISSUE THREAD

**Issue by prvst** [BioContainers/containers#65]
Hi @BioDocker/contributors 

Since we are moving to a Conda/BioConda management system for our binaries, I want to clean the base image. Currently, our base image has 1.036 GB, so that means its pretty bloated. How can we start doing that? should we clean the apt-get command and then fix the ones that break? Suggestions are welcome.

**Comment by thriqon** [comment]
Have you considered adopting a leaner build setup instead of the 'traditional' Dockerfiles? My thesis explains a different approach quite extensively, if you want to read I can send it you.

/cc: @bgruening

**Comment by ypriverol** [comment]
ypriverol@gmail.com

**Comment by bgruening** [comment]
@thriqon I told you about the meeting today with the biodocker team :)
We have drafted a plan for the way forward and this looks indeed really nice. Will try to call you tomorrow.

**Comment by thriqon** [comment]
@bgruening, I know and thanks, but I was unable to make it... Looking forward to the plan!

**Comment by ypriverol** [comment]
@prvst @thriqon @bgruening for now we can clean the base image to make it smaller. and install only the package needed. After this as @bgruening mention we can move things forward.
