### ISSUE TITLE
(ERR): bowtie2-align exited with value 141

### ISSUE THREAD

**Issue by lucafromthespace** [BioContainers/containers#68]
i'm running the following command 
~/Softwares/bismark/bismark -n 1 --path_to_bowtie ~/Softwares/bowtie2 --samtools_path  ~/Softwares/samtools  ~/Softwares/rat_genome/rn5 ~/Softwares/trim_galore/C8Y92ACXX.sequence.fastq

and i'm getting all the time this error: 
(ERR): bowtie2-align exited with value 141

**Comment by prvst** [comment]
Hi @lucafromthespace , can you confirm to me which container you are using and also the docker command you are running? I don't see them in your comment above.

**Comment by prvst** [comment]
Hi @lucafromthespace , did you ran the program successfully?
