### ISSUE TITLE
New containers

### ISSUE THREAD

**Issue by leobiscassi** [BioContainers/containers#69]
Hi everyone, I'm working in two containers, one is about [GROMACS](http://www.gromacs.org/) and other is about [GAMESS](http://www.msg.ameslab.gov/gamess/download.html). This containers are interesting to the project?

**Comment by prvst** [comment]
Hi @leobiscassi ;

Fell free to contribute with the software you have, we do not select software based on our interests, the idea is to provide support, standards and documentation for others to provide containers with your own tools, doesn't matter if you are the only one using them.

Just in case you are not one of the authors behind these software, please check if there is any restriction in their licenses.

Please follow the instructions [here](https://github.com/BioDocker/biodocker/wiki), to make your containers.

Feel free to contact us if you need any kind os assistance ( I can also help you in Portuguese! )

**Comment by leobiscassi** [comment]
Hi @prvst , thanks for your reply! I will check with the authors about using the softwares in these containers and follow the instructions to build my containers!
Oh, really!? Great news, my english is bad yet, rsrsrs.

**Comment by ypriverol** [comment]
@prvst just to add to @prvst idea. should be bioinformatics and also complaint with the specification.

**Comment by leobiscassi** [comment]
hi @ypriverol, in fact, I made the question if my containers are interesting for the project because are about computational physics and computational chemistry. Can I submit them when I finish the work or not? :sweat_smile: 
Thanks for the help!

**Comment by ypriverol** [comment]
Yes Please!!! also feel free to take other computational chemistry software and move it to BioDocker, Docking, virtual screening and chemo-informatics in general is more than welcome.

**Comment by leobiscassi** [comment]
oh great! thanks! :smiley:
