### ISSUE TITLE
Adopting LABEL for metadata

### ISSUE THREAD

**Issue by prvst** [BioContainers/containers#70]
@BioDocker/contributors, Docker allows us to use the LABELS command to add metadata to images. This can be used in searched via docker client and it can aso be used by the API.

You can read more about it [here](https://docs.docker.com/engine/userguide/labels-custom-metadata/).

So, my question here is; Should we add this command to the metadata we already have in our Dockerfiles ? What do you think?

**Comment by bgruening** [comment]
Makes sense, but we should base this on an ontology to standardize it. bio.tools?

**Comment by prvst** [comment]
moving this issue to biocontainers/specs, issue 68
