### ISSUE TITLE
biodocker and ubuntu 16.04

### ISSUE THREAD

**Issue by rjpbonnal** [BioContainers/containers#72]
Is it possible to update biodocker to the latest LTS or maybe keep the old and a latest container to build containers with updated software ?

**Comment by prvst** [comment]
Hi @helios 
It is on our plans to update the Ubuntu version for the base image. We just decided to wait for a few month for all the last-time updates and bug fixes to come out.

**Comment by rjpbonnal** [comment]
It makes sense.
The question arose because I was trying to install circos and the official release for 14.04 is almost outdated. I would not say that is not possible to use 14.04 for scratch installation but after few hours of testing I realised that 16.04 has the latest release of that software. Maybe is possible to have some sort of multiple release with different distributions with special "tag" referring to "stability".

**Comment by prvst** [comment]
that's something that we can discuss, @ypriverol , @sauloal , but in fact we want to avoid having multiple base images.
But it was good that you sent this questions, I think I can update the base image during the weekend, I will let you know.

**Comment by prvst** [comment]
@helios btw, it would be great to have Circos on our container list, I would love if you could share that with us :)

**Comment by ghost** [comment]
I would also strongly support having Circos (circus.ca) on the container list.  This is a fantastic tool with an extremely broad audience.

**Comment by rjpbonnal** [comment]
@prvst  In the mean time, I will try to install circos from scratch, actually i was almost done except for perl and GD; I'll do a pull request to the main repo when circos (latest) will be ready for 14.04.

**Comment by prvst** [comment]
Hi @BioDocker/contributors ,

Yesterday I updated our base image to Ubuntu 16.04. I'm getting some failure reports from DockerHub saying that some containers are not building, I will try to fix them in the following days.
