### ISSUE TITLE
rkt is failling

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/containers#79]
@bgruening I have try to download a container is quay.io using rkt and I'm receiving the following error: 

> rkt fetch --no-store quay.io/biocontainers/bedtools
> image: searching for app image quay.io/biocontainers/bedtools
> image: remote fetching from URL "https://quay.io/c1/aci/quay.io/biocontainers/bedtools/latest/aci/linux/amd64/"
> image: keys already exist for prefix "quay.io/biocontainers/bedtools", not fetching again
> image: downloading signature from https://quay.io/c1/aci/quay.io/biocontainers/bedtools/latest/aci.asc/linux/amd64/
> fetch: bad HTTP status code: 404

**Comment by bgruening** [comment]
Try `rkt fetch --no-store quay.io/biocontainers/bedtools:2.25.0--2`
