### ISSUE TITLE
latest tag not available for certain containers built from mulled

### ISSUE THREAD

**Issue by pcm32** [BioContainers/containers#81]
Trying to execute:

```
docker pull quay.io/biocontainers/openbabel
```

gives

```
Using default tag: latest
Pulling repository quay.io/biocontainers/openbabel
Tag latest not found in repository quay.io/biocontainers/openbabel
```

However, the registry-ui recommends to pull with that command, see container pull command [here](http://biocontainers.pro/registry/#/showImages?domain=quay&repository=openbabel&starred=false&modified=05%2F11%2F2016).

**Comment by ypriverol** [comment]
@bgruening do you know why the quay.io containers do not have the latest version?

**Comment by bgruening** [comment]
We simply did not implement it. In theory this should be easy we could simply link "some" container to the `:latest` version. The tricky question is how to determine what is the `latest` version. Depending on the version schema this can be tricky. But the most important part is at which time point to we want to create this link? On the bioconda side - when a new container is pushed? As a separate service?

Is this an important feature to have? Can we not solve this with tooling? For example `mulled-search` returns an entire command which you can use, including the correct version.

**Comment by ypriverol** [comment]
ok. I think the main point is that we need to make clear in the interface of the registry UI which is the version because right now is building the docker command taking into account that latest exists.

**Comment by pcm32** [comment]
Yes, my point was more towards what @ypriverol wrote, if the UI advertises a pull command, then it should work out of copy pasting the command. If you don't want to have a latest, then the (registry) UI should point to a version in the pull command, that's all.

Whether to have a latest or not, I guess it is a separate discussion. My quick thought on this would be that not having a latest might not be a good idea considering that people used to docker containers probably expect to find it. And then, using a version on the UI's pull command is more or less analogous to choosing a latest, you're still "blessing" a version. Question is whether the UI or the container maintainer should decide this, probably the latter in my opinion.

**Comment by bgruening** [comment]
> Question is whether the UI or the container maintainer should decide this, probably the latter in my opinion.

There is no container maintainer anymore, this needs to happen completely automatically and this is where I'm a little bit afraid. I think the quick way is to fix the UI and if someone has time we could implement a mechanism to update the `latest` version somehow. I know that the quay.io API supports this - I just don't have time the next month I think :(

**Comment by pcm32** [comment]
Yes, I understand where you come from. Do you have different branches or channels for the containers? such as master and develop? or stable and bleeding edge? Maybe every time that the master/stable is built, that container could be blessed as latest.

**Comment by bgruening** [comment]
Oh no, I have a bioconda package and as soon as this is available I create a container for it :)
Problem is that you can add Conda package for old software, what we did to migrate a lot of Galaxy tools to Conda ... this means the latest Conda package that was build for tool X does not mean it should be `latest`.

**Comment by ypriverol** [comment]
Ok @bgruening but can we add this tag to the bioconda recipe and then used during the creating of the container?

**Comment by bgruening** [comment]
Wich tag? If you add `latest` to all recipes, all will end up as `latest` :)

**Comment by iSnow** [comment]
So, how do I go about pulling and starting a biocontainers docker image? And pardon my ignorance, what is `mulled-search`? Looking for it at Google leads me to a lot of wine sites, but no software.

I am specifically looking at running the openbabel container from quay.io, would it be possible to attach a bit more information, like how to pull any recent image? Or does it include a REST service and on which port does it run or do you link in a path like in the BLAST example?

Biocontainers seems like a very nice and useful project, however a bit developer-centric right now. So, adding some end-user information would be awesome :)

Thanks for all your work!

**Comment by ypriverol** [comment]
Thans @iSnow for using BioContainers. The point for searching a container in the web is: http://biocontainers.pro/registry/#/, there you can search for the corresponding container. For example a search there will give you the openbabel container 
(http://biocontainers.pro/registry/#/showImages?domain=quay&repository=openbabel&starred=false&modified=05%2F11%2F2016). 

We will update the documentation here biocontainers.pro/docs but feel free to suggest and contribute to it. We are now discussing how to add a default tag to each mulled container.

**Comment by ypriverol** [comment]
@bgruening and @pcm32 I have been thinking about adding the specific tag to the UI now but, for best practices, I think it will be good to have the latest version of each mulled container. If I try to do that in the UI it will be also a guessing process. Then I really think we should do this systematically. How we can implement this @bgruening

**Comment by bgruening** [comment]
@iSnow I have added a more obvious statement how you can install the utilities in https://github.com/BioContainers/edu/blob/master/series/faqs/galaxy_container_dependencies.md

Essentially, mulled-search and all the other tooling is currently part of galaxy-lib:

```
pip install galaxy-lib
```

@ypriverol the problem is that it is not easy to guess the most recent version, because naming schema are not standardized. So we will make mistakes.
