### ISSUE TITLE
TPP 5.0

### ISSUE THREAD

**Issue by ypriverol** [BioContainers/containers#85]
_From @edeutsch on January 20, 2017 5:3_

Hi, I see that you have the Trans-Proteomic Pipeline (TPP) as a container, but it is an older version 4.8. There is now a 5.0 version of TPP out. Can we get new TPP 5.0 containers available? How can we help?

thanks,
Eric

_Copied from original issue: BioContainers/sandbox#74_

**Comment by ypriverol** [comment]
_From @prvst on January 20, 2017 14:43_

Hey @edeutsch ;

TPP 5.0 is definitively on our TODO list, unfortunately it seems that the new version requires some extra work in order to be installed on a Linux environment. 

If you have any initial work on that, feel free to submit it to the containers list, you will be noted as the author of the container.

**Comment by ypriverol** [comment]
_From @edeutsch on January 20, 2017 17:55_

I don't quite understand what you mean. I don't know how to interpret "submit it to the containers list". I have no experience making a container, but am happy to learn more. As far as building/installing TPP 5.0, here is a recipe for building on Ubuntu 16.04:
http://tools.proteomecenter.org/wiki/index.php?title=TPP_5.0.0:_Installing_on_Ubuntu_16.04
Does that help?

**Comment by ypriverol** [comment]
_From @prvst on January 20, 2017 19:31_

Hi @edeutsch ;

Sorry for that, let me explain a little better; Our project is open to the community, that means anyone can join in and participate. If you don't know how to create containers we can help you, if you do, the only think you need to do is PR with your work. Some of the people who collaborate by adding new containers fork our repos, add their work and then send them back to us. When you asked how to help, I understand that you wanted to add something to the list, my bad =)

Having said that, we can help you to create one or , depending on the situation we can get the guidelines from you and make one ourselves. This usually happens when the developers don't know how to work with Docker yet but they want to contribute somehow. If you wish to learn more about this, please check our [Wiki](https://github.com/BioContainers/specs/wiki).

That website you sent is new to me, I remember to have seen something similar around GitHub. Since it envolves a lot of steps, I didn't tried yet. As soon as I have time, I will start working on that.

Please, feel free to get in touch in case you need something.
Thanks for sending the guide

**Comment by prvst** [comment]
Dear @edeutsch;

The new TPP 5.0 container is already available via Docker client, please note that the web interface is not operational, only the binaries from /usr/local/tpp/bin are usable.

Please feel free to get in touch if you find any problem.

Sorry for the long delay
